package engine

// Aliases for moonhug:host/core. Core holds the dependency-free vocabulary
// (handles, pools, type keys, refs) so packages can use it without importing
// the engine.
//
// Rules:
// - An alias makes engine.<name> and unqualified engine-internal references
//   resolve to the core declaration. engine.Handle and core.Handle are the
//   same type.
// - Aliases cover the core names the engine uses. A core name the engine
//   does not use gets no alias.
// - Global variables have no aliases (Odin aliases types and procs only).
//   Access the registry maps as core.<name> or through the accessor procs.

import core "moonhug:host/core"
import assets "moonhug:host/assets"

// Lifecycle phases (enum generated by phase_gen, declared in core/phases.odin).
Phase :: core.Phase

// Application state (application.odin in core; isEditor and isPlaying are
// on UserContext).
application_is_focused       :: core.application_is_focused

// Type keys and the type registry.
TypeKey                      :: core.TypeKey
INVALID_TYPE_KEY             :: core.INVALID_TYPE_KEY
TypeMeta                     :: core.TypeMeta
FieldInfo                    :: core.FieldInfo
register_type                :: core.register_type
register_pointer_type        :: core.register_pointer_type
register_type_key            :: core.register_type_key
get_typeid_by_type_key       :: core.get_typeid_by_type_key
get_guid_by_type_key         :: core.get_guid_by_type_key
get_typeMeta_by_type_key     :: core.get_typeMeta_by_type_key
get_pointerType_by_type_key  :: core.get_pointerType_by_type_key
get_type_key_by_typeid       :: core.get_type_key_by_typeid
type_keys_registered         :: core.type_keys_registered
get_guid_by_typeid           :: core.get_guid_by_typeid
json_canonicalize_floats     :: core.json_canonicalize_floats
get_typeid_by_guid           :: core.get_typeid_by_guid
get_typeid_by_guid_ok        :: core.get_typeid_by_guid_ok
get_pointer_typeid_by_typeid :: core.get_pointer_typeid_by_typeid
create_zero_instance_by_type_key   :: core.create_zero_instance_by_type_key
create_zero_instance_by_guid       :: core.create_zero_instance_by_guid
create_instance_by_type_key  :: core.create_instance_by_type_key
create_instance_by_guid      :: core.create_instance_by_guid
type_register_reset          :: core.type_register_reset
type_register_cleanup        :: core.type_register_cleanup
type_register_on_validate    :: core.type_register_on_validate
type_has_reset               :: core.type_has_reset
type_has_cleanup             :: core.type_has_cleanup
type_reset                   :: core.type_reset
type_cleanup                 :: core.type_cleanup
type_cleanup_by_typeid       :: core.type_cleanup_by_typeid
type_on_validate             :: core.type_on_validate
type_on_validate_by_typeid   :: core.type_on_validate_by_typeid
generate_type_info           :: core.generate_type_info
typeid_to_u16                :: core.typeid_to_u16

// Object references.
Local_ID            :: core.Local_ID
Asset_GUID          :: core.Asset_GUID
PPtr                :: core.PPtr
Ref_Local           :: core.Ref_Local
Ref                 :: core.Ref
Owned               :: core.Owned
asset_guid_is_empty :: core.asset_guid_is_empty

// Handles and pools.
MAX              :: core.MAX
Handle           :: core.Handle
Transform_Handle :: core.Transform_Handle
Pool             :: core.Pool
Pool_Iterator    :: core.Pool_Iterator
Pool_Entry       :: core.Pool_Entry
pool_init        :: core.pool_init
pool_create      :: core.pool_create
pool_destroy     :: core.pool_destroy
pool_get         :: core.pool_get
pool_get_assert  :: core.pool_get_assert
pool_valid       :: core.pool_valid
pool_iterator    :: core.pool_iterator
pool_next        :: core.pool_next
pool_make_entry  :: core.pool_make_entry

// Component base.
CompData  :: core.CompData
comp_zero :: core.comp_zero

// Bidirectional map.
Bimap               :: core.Bimap
bimap_insert        :: core.bimap_insert
bimap_remove        :: core.bimap_remove
bimap_remove_by_key :: core.bimap_remove_by_key
bimap_remove_by_val :: core.bimap_remove_by_val
bimap_get           :: core.bimap_get
bimap_has           :: core.bimap_has
cleanup_Bimap       :: core.cleanup_Bimap

// Quaternion helpers ([4]f32 xyzw <-> native, euler degrees).
QUAT_IDENTITY       :: core.QUAT_IDENTITY
quat_to_native      :: core.quat_to_native
quat_from_native    :: core.quat_from_native
quat_to_matrix3     :: core.quat_to_matrix3
quat_from_euler_xyz :: core.quat_from_euler_xyz
quat_to_euler_xyz   :: core.quat_to_euler_xyz
quaternion128_x     :: core.quaternion128_x
quaternion128_y     :: core.quaternion128_y
quaternion128_z     :: core.quaternion128_z
quaternion128_w     :: core.quaternion128_w

// Settings persistence (core/project_settings.odin, core/user_settings.odin).
PROJECT_SETTINGS_DIR  :: core.PROJECT_SETTINGS_DIR
USER_SETTINGS_DIR     :: core.USER_SETTINGS_DIR
project_settings_file :: core.project_settings_file
project_settings_load :: core.project_settings_load
project_settings_save :: core.project_settings_save
user_settings_file    :: core.user_settings_file
user_settings_load    :: core.user_settings_load
user_settings_save    :: core.user_settings_save

// Inspector state and request mailboxes (core/inspector_state.odin).
inspector_push_readonly             :: core.inspector_push_readonly
inspector_pop_readonly              :: core.inspector_pop_readonly
inspector_is_readonly               :: core.inspector_is_readonly
inspector_set_nested_host           :: core.inspector_set_nested_host
inspector_get_nested_host           :: core.inspector_get_nested_host
inspector_set_nested_local_id       :: core.inspector_set_nested_local_id
inspector_get_nested_local_id       :: core.inspector_get_nested_local_id
inspector_set_active_selection      :: core.inspector_set_active_selection
inspector_active_selection          :: core.inspector_active_selection
inspector_set_inspected_selection   :: core.inspector_set_inspected_selection
inspector_inspected_selection       :: core.inspector_inspected_selection
inspector_request_select            :: core.inspector_request_select
inspector_take_pending_select       :: core.inspector_take_pending_select
inspector_request_ping              :: core.inspector_request_ping
inspector_take_pending_ping         :: core.inspector_take_pending_ping
inspector_request_select_asset      :: core.inspector_request_select_asset
inspector_take_pending_select_asset :: core.inspector_take_pending_select_asset
inspector_request_ping_asset        :: core.inspector_request_ping_asset
inspector_take_pending_ping_asset   :: core.inspector_take_pending_ping_asset
inspector_request_open_asset        :: core.inspector_request_open_asset
inspector_take_pending_open_asset   :: core.inspector_take_pending_open_asset

// Curves and gradients (core/curve.odin).
Curve                               :: core.Curve
Curve_Key                           :: core.Curve_Key
Gradient                            :: core.Gradient
Gradient_Key                        :: core.Gradient_Key
MinMax_Curve                        :: core.MinMax_Curve
MinMax_Mode                         :: core.MinMax_Mode
curve_eval                          :: core.curve_eval
gradient_eval                       :: core.gradient_eval
minmax_constant                     :: core.minmax_constant
minmax_range                        :: core.minmax_range
minmax_eval                         :: core.minmax_eval
minmax_cleanup                      :: core.minmax_cleanup

// Reference picker candidates (core/object_ref.odin).
Found_Object                 :: core.Found_Object
Scene_Ref                    :: core.Scene_Ref

// Camera math (core/view_math.odin, core/raycast.odin).
View_Kind                    :: core.View_Kind
Render_View                  :: core.Render_View
Ray                          :: core.Ray
render_view_make             :: core.render_view_make
render_view_screen_ray       :: core.render_view_screen_ray
trs_matrix                   :: core.trs_matrix
ray_hit_aabb                 :: core.ray_hit_aabb
ray_hit_triangle             :: core.ray_hit_triangle

// Gizmo vocabulary and buffer (core/gizmo_buffer.odin), fixed tick flag.
Gizmo_Batch                  :: core.Gizmo_Batch
Gizmo_Buffer                 :: core.Gizmo_Buffer
Gizmo_Channel                :: core.Gizmo_Channel
Gizmo_Clock                  :: core.Gizmo_Clock
Gizmo_Group                  :: core.Gizmo_Group
Gizmo_Icon                   :: core.Gizmo_Icon
Gizmo_Icon_Image             :: core.Gizmo_Icon_Image
Gizmo_Label                  :: core.Gizmo_Label
Gizmo_Lifetime               :: core.Gizmo_Lifetime
Gizmo_Prim                   :: core.Gizmo_Prim
Gizmo_Prim_Kind              :: core.Gizmo_Prim_Kind
Gizmo_Symbol                 :: core.Gizmo_Symbol
gizmo_batch_clear            :: core.gizmo_batch_clear
gizmo_buffer                 :: core.gizmo_buffer
gizmo_buffer_clear_clock     :: core.gizmo_buffer_clear_clock
gizmo_buffer_clear_key       :: core.gizmo_buffer_clear_key
gizmo_buffer_clear_lifetime  :: core.gizmo_buffer_clear_lifetime
gizmo_buffer_destroy         :: core.gizmo_buffer_destroy
gizmo_buffer_frame_boundary  :: core.gizmo_buffer_frame_boundary
gizmo_buffer_key_group       :: core.gizmo_buffer_key_group
gizmo_buffer_sync_frame      :: core.gizmo_buffer_sync_frame
gizmo_buffer_timed_group     :: core.gizmo_buffer_timed_group
gizmo_clock_now              :: core.gizmo_clock_now
fixed_in_tick                :: core.fixed_in_tick

// Asset database and the pipeline's read half (moonhug:host/assets). The
// database variable has no alias: read it as assets.asset_db.
AssetDB                           :: assets.AssetDB
Asset_File_Stamp                  :: assets.Asset_File_Stamp
Asset_Root_Info                   :: assets.Asset_Root_Info
Asset_Index_Entry                 :: assets.Asset_Index_Entry
Asset_Indexer                     :: assets.Asset_Indexer
Asset_Package_Root                :: assets.Asset_Package_Root
Asset_Pipeline_Kind               :: assets.Asset_Pipeline_Kind
Asset_Gone_Hook                   :: assets.Asset_Gone_Hook
Evict_Hook                        :: assets.Evict_Hook
ImportMeta                        :: assets.ImportMeta
MetaFile                          :: assets.MetaFile
Path_Changed_Hook                 :: assets.Path_Changed_Hook
Reimport_Hook                     :: assets.Reimport_Hook
Sub_Asset_Decl                    :: assets.Sub_Asset_Decl
Sub_Asset_Ref                     :: assets.Sub_Asset_Ref

LIBRARY_DIR                       :: assets.LIBRARY_DIR
ARTIFACTS_DIR                     :: assets.ARTIFACTS_DIR
ARTIFACT_DB_PATH                  :: assets.ARTIFACT_DB_PATH
ASSET_CATALOG_PATH                :: assets.ASSET_CATALOG_PATH
ASSET_DB_PACKAGES_DIR             :: assets.ASSET_DB_PACKAGES_DIR

// The project root (assets/project_root.odin): every relative path resolves
// against it.
project_root_find                 :: assets.project_root_find
project_chdir_root                :: assets.project_chdir_root

asset_db_init                     :: assets.asset_db_init
asset_db_shutdown                 :: assets.asset_db_shutdown
asset_db_init_from_catalog        :: assets.asset_db_init_from_catalog
asset_db_boot_scene               :: assets.asset_db_boot_scene
asset_db_package_roots            :: assets.asset_db_package_roots
asset_db_get_path                 :: assets.asset_db_get_path
asset_db_get_guid                 :: assets.asset_db_get_guid
asset_db_get_root_info            :: assets.asset_db_get_root_info
asset_db_get_stamp                :: assets.asset_db_get_stamp
asset_db_get_sub                  :: assets.asset_db_get_sub
asset_db_sub_guid                 :: assets.asset_db_sub_guid
asset_db_new_guid                 :: assets.asset_db_new_guid
asset_db_set_subs                 :: assets.asset_db_set_subs
asset_db_assets_with_root_type    :: assets.asset_db_assets_with_root_type
asset_db_add_indexer              :: assets.asset_db_add_indexer
asset_db_index_set                :: assets.asset_db_index_set
asset_db_reindex                  :: assets.asset_db_reindex
asset_db_add_evict_hook           :: assets.asset_db_add_evict_hook
asset_db_run_evict_hooks          :: assets.asset_db_run_evict_hooks
asset_db_add_path_changed_hook    :: assets.asset_db_add_path_changed_hook
asset_db_add_asset_gone_hook      :: assets.asset_db_add_asset_gone_hook
asset_db_set_refresh_proc         :: assets.asset_db_set_refresh_proc
asset_db_request_refresh          :: assets.asset_db_request_refresh
asset_catalog_write               :: assets.asset_catalog_write
asset_pipeline_get_settings       :: assets.asset_pipeline_get_settings
asset_pipeline_artifact_key       :: assets.asset_pipeline_artifact_key
asset_pipeline_artifact_path      :: assets.asset_pipeline_artifact_path
asset_pipeline_add_reimport_hook  :: assets.asset_pipeline_add_reimport_hook
asset_pipeline_set_import_request :: assets.asset_pipeline_set_import_request
asset_pipeline_request_import     :: assets.asset_pipeline_request_import

_register_asset                   :: assets._register_asset
_register_sub                     :: assets._register_sub
_unregister_subs_of               :: assets._unregister_subs_of
_asset_removed                    :: assets._asset_removed
_read_meta                        :: assets._read_meta
_write_meta                       :: assets._write_meta
_generate_guid                    :: assets._generate_guid
_read_import_meta                 :: assets._read_import_meta
_settings_overlay                 :: assets._settings_overlay
_settings_from_value              :: assets._settings_from_value
_artifact_path                    :: assets._artifact_path
_artifact_key_path                :: assets._artifact_key_path
_artifact_index_ensure            :: assets._artifact_index_ensure
_artifact_index_lookup            :: assets._artifact_index_lookup
_artifact_index_set               :: assets._artifact_index_set
_artifact_index_save              :: assets._artifact_index_save
_artifact_index_prune             :: assets._artifact_index_prune
_artifact_index_batch_set         :: assets._artifact_index_batch_set
_artifact_index_seed              :: assets._artifact_index_seed
_ensure_artifact_dir              :: assets._ensure_artifact_dir
_cleanup_stale_artifacts          :: assets._cleanup_stale_artifacts
_notify_reimported                :: assets._notify_reimported
_catalog_settings_set             :: assets._catalog_settings_set
_catalog_pipeline_reset           :: assets._catalog_pipeline_reset
_asset_catalog_auto_write         :: assets._asset_catalog_auto_write
