package engine

// Code generated by tween_gen. Do not edit.

@(poolable)
@(typ_guid={guid="a243efe5-6e34-4d1c-886c-83928685df48"})
TweenUnion :: union #no_nil{
	Tween,
	Parallel,
	Sequence,
	TweenMoveToLocal,
	TweenRotateToLocal,
	TweenScaleToLocal,
}

__tween_ticks_init :: proc()
{
	tween_runner_setup()

	_tween_runner.ticks[int(TypeKey.Parallel)] = tick_Parallel
	_tween_runner.ticks[int(TypeKey.Sequence)] = tick_Sequence
	_tween_runner.ticks[int(TypeKey.TweenMoveToLocal)] = tick_TweenMoveToLocal
	_tween_runner.ticks[int(TypeKey.TweenRotateToLocal)] = tick_TweenRotateToLocal
	_tween_runner.ticks[int(TypeKey.TweenScaleToLocal)] = tick_TweenScaleToLocal

	_tween_runner.frees[int(TypeKey.Parallel)] = tween_free_Parallel
	_tween_runner.frees[int(TypeKey.Sequence)] = tween_free_Sequence
}
