package sim_host_gen

// sim_host_gen: the table of runnable packages the editor can tick, written
// into the registration bundle. A host generator, not the engine's: the table
// must exist with no engine installed, and a plugin's generator cannot own a
// host file.


// sim_host_gen: the editor's table of simulation hosts (docs/core/Plugins.md) — the
// installed packages whose root declares `main`.
//
//   generate - moonhug/registration/sim_hosts_generated.odin: `sim_hosts`, one
//              Sim_Host row per runnable package with that host's __update /
//              __fixed_update. The table lives in the all-packages bundle, which
//              already imports every runtime package, so the engine plugin never
//              imports a game. sim_world converts the rows to simulate.Host and
//              hands them to editor/simulate.
//
// Other dispatchers are emitted per host under a fixed name, unambiguous inside a
// game binary. The editor is not a host and links all of them, so which host to
// tick is a runtime choice: editor/simulate reads the selected row's procs, and
// the Sim Host dropdown lists them.

import "core:fmt"
import "core:strings"
import "../gen_core"
import db "../gen_db"
import "../gen_facts"

_SIM_HOSTS_OUT_FILE :: "moonhug/registration/sim_hosts_generated.odin"

// Generated files are not committed, so a checkout can still hold the copies
// older prebuilds wrote into the editor root and into sim_world. Nothing reads
// their tables any more, so generate removes them.
_SIM_HOSTS_STALE_FILES := []string{
	"moonhug/editor/sim_hosts_generated.odin",
	"moonhug/packages/engine/editor/sim_world/sim_hosts_generated.odin",
}

@(init)
_register_sim_host :: proc "contextless" () {
	db.generator("sim_host/generate", sim_host_generate)
}

sim_host_generate :: proc(w: ^db.World) -> bool {
	hosts := gen_facts.runnable_packages(w)
	defer delete(hosts)

	b := strings.builder_make()
	defer strings.builder_destroy(&b)

	strings.write_string(&b, "package registration\n\n")
	strings.write_string(&b, "// Code generated by sim_host_gen. Do not edit.\n")
	strings.write_string(&b, "// One row per runnable package (docs/core/Plugins.md) - the games the editor\n")
	strings.write_string(&b, "// can tick. Entry points come from that host's update_generated.odin.\n\n")

	for h in hosts {
		// The `moonhug` collection maps to the moonhug/ folder, so the import is the
		// scan path minus that prefix (the form update_gen emits).
		fmt.sbprintf(&b, "import %s \"moonhug:packages/%s\"\n", h.name, h.name)
	}
	strings.write_string(&b, "\n")

	// A slice, not a map: the set is fixed at build time and the dropdown needs a
	// stable order. runnable_packages sorts by name, so row 0 is deterministic.
	// The row type is local: registration imports runtime packages only, never
	// the editor shell that declares simulate.Host.
	strings.write_string(&b, "Sim_Host :: struct {\n")
	strings.write_string(&b, "\tname:         string,\n")
	strings.write_string(&b, "\tpath:         string,\n")
	strings.write_string(&b, "\tupdate:       proc(dt: f32),\n")
	strings.write_string(&b, "\tfixed_update: proc(dt: f32),\n")
	strings.write_string(&b, "}\n\n")
	strings.write_string(&b, "sim_hosts := []Sim_Host{\n")
	for h in hosts {
		fmt.sbprintf(&b, "\t{{\"%s\", \"%s\", %s.__update, %s.__fixed_update},\n",
			h.name, h.path, h.name, h.name)
	}
	strings.write_string(&b, "}\n")

	db.emit(w, _SIM_HOSTS_OUT_FILE, strings.to_string(b))
	for stale in _SIM_HOSTS_STALE_FILES do gen_core.RemoveStaleFile(stale)
	return true
}
