package sim_host_gen

// host_gen: gives the EDITOR a table of the SIMULATION HOSTS (docs/Plugins.md) —
// the installed packages whose root declares `main`, i.e. the games.
//
//   generate - moonhug/editor/sim_hosts_generated.odin: `sim_hosts`, one row per
//              runnable package, each carrying that host's generated entry
//              points (__update / __fixed_update from update_gen).
//
// Why this exists: every OTHER generated dispatcher is emitted per host, into
// that host's own package, under a fixed name (`__update`, `phase_run`, …). That
// works for the app binary, which IS one host. The editor is not a host and
// links all of them, so "which host?" is a runtime choice there — and without a
// table the editor can only hardcode one, which silently ticks the wrong game
// once a second host exists.
//
// The table is the editor's only way to answer that question. Simulate
// (editor/simulate.odin) reads the selected row's procs; the Sim Host dropdown
// in the toolbar is this list.

import "core:fmt"
import "core:strings"
import db "../gen_db"
import "../gen_facts"

@(init)
_register :: proc "contextless" () {
	db.generator("sim_host/generate", generate)
}

generate :: proc(w: ^db.World) -> bool {
	hosts := gen_facts.runnable_packages(w)
	defer delete(hosts)

	b := strings.builder_make()
	defer strings.builder_destroy(&b)

	strings.write_string(&b, "package editor\n\n")
	strings.write_string(&b, "// Code generated by sim_host_gen. Do not edit.\n")
	strings.write_string(&b, "// One row per runnable package (docs/Plugins.md) - the games the editor\n")
	strings.write_string(&b, "// can tick. Entry points come from that host's update_generated.odin.\n\n")

	for h in hosts {
		// The collection maps `moonhug` to the moonhug/ folder, so the import is
		// the scan path with that prefix dropped (same form update_gen emits).
		fmt.sbprintf(&b, "import %s \"moonhug:packages/%s\"\n", h.name, h.name)
	}
	if len(hosts) > 0 do strings.write_string(&b, "\n")

	strings.write_string(&b, "Sim_Host :: struct {\n")
	strings.write_string(&b, "\tname:         string,        // package name, e.g. \"app\"\n")
	strings.write_string(&b, "\tpath:         string,        // scan path, e.g. \"moonhug/packages/app\"\n")
	strings.write_string(&b, "\tupdate:       proc(dt: f32), // that host's __update\n")
	strings.write_string(&b, "\tfixed_update: proc(dt: f32), // that host's __fixed_update\n")
	strings.write_string(&b, "}\n\n")

	// A slice literal rather than a map: the set is fixed at build time, tiny,
	// and needs a stable order for the dropdown. Sorted by name by
	// runnable_packages, so row 0 is a deterministic default.
	strings.write_string(&b, "sim_hosts := []Sim_Host{\n")
	for h in hosts {
		fmt.sbprintf(&b, "\t{{\"%s\", \"%s\", %s.__update, %s.__fixed_update},\n",
			h.name, h.path, h.name, h.name)
	}
	strings.write_string(&b, "}\n")

	db.emit(w, "moonhug/editor/sim_hosts_generated.odin", strings.to_string(b))
	return true
}
