package sim_host_gen

// sim_host_gen: the editor's table of simulation hosts (docs/Plugins.md) — the
// installed packages whose root declares `main`.
//
//   generate - moonhug/editor/sim_hosts_generated.odin: `sim_hosts`, one row per
//              runnable package with that host's __update / __fixed_update.
//
// Other dispatchers are emitted per host under a fixed name, unambiguous inside a
// game binary. The editor is not a host and links all of them, so which host to
// tick is a runtime choice: editor/simulate reads the selected row's procs, and
// the Sim Host dropdown lists them.

import "core:fmt"
import "core:strings"
import db "../gen_db"
import "../gen_facts"

@(init)
_register :: proc "contextless" () {
	db.generator("sim_host/generate", generate)
}

generate :: proc(w: ^db.World) -> bool {
	hosts := gen_facts.runnable_packages(w)
	defer delete(hosts)

	b := strings.builder_make()
	defer strings.builder_destroy(&b)

	strings.write_string(&b, "package editor\n\n")
	strings.write_string(&b, "// Code generated by sim_host_gen. Do not edit.\n")
	strings.write_string(&b, "// One row per runnable package (docs/Plugins.md) - the games the editor\n")
	strings.write_string(&b, "// can tick. Entry points come from that host's update_generated.odin.\n\n")

	for h in hosts {
		// The `moonhug` collection maps to the moonhug/ folder, so the import is the
		// scan path minus that prefix (the form update_gen emits).
		fmt.sbprintf(&b, "import %s \"moonhug:packages/%s\"\n", h.name, h.name)
	}
	if len(hosts) > 0 do strings.write_string(&b, "\n")

	strings.write_string(&b, "Sim_Host :: struct {\n")
	strings.write_string(&b, "\tname:         string,        // package name, e.g. \"app\"\n")
	strings.write_string(&b, "\tpath:         string,        // scan path, e.g. \"moonhug/packages/app\"\n")
	strings.write_string(&b, "\tupdate:       proc(dt: f32), // that host's __update\n")
	strings.write_string(&b, "\tfixed_update: proc(dt: f32), // that host's __fixed_update\n")
	strings.write_string(&b, "}\n\n")

	// A slice, not a map: the set is fixed at build time and the dropdown needs a
	// stable order. runnable_packages sorts by name, so row 0 is deterministic.
	strings.write_string(&b, "sim_hosts := []Sim_Host{\n")
	for h in hosts {
		fmt.sbprintf(&b, "\t{{\"%s\", \"%s\", %s.__update, %s.__fixed_update},\n",
			h.name, h.path, h.name, h.name)
	}
	strings.write_string(&b, "}\n")

	db.emit(w, "moonhug/editor/sim_hosts_generated.odin", strings.to_string(b))
	return true
}
