package app

// Code generated by packages_gen. Do not edit.
// Installed packages (moonhug/packages/*) — see docs/Plugins.md.

import _ "moonhug:packages/audio"
import _ "moonhug:packages/essentials"
import _ "moonhug:packages/node_graph"
import physics2d "moonhug:packages/physics2d"
import _ "moonhug:packages/physics2d_sample"
import physics3d "moonhug:packages/physics3d"
import _ "moonhug:packages/physics3d_sample"
import plugin_example "moonhug:packages/plugin_example"
import _ "moonhug:packages/prefabs_example"
import _ "moonhug:packages/tween"

register_packages :: proc() {
	register_app_components()
	physics2d.register_physics2d_components()
	physics3d.register_physics3d_components()
	plugin_example.register_plugin_example_components()
}
