package app

// Code generated by phase_gen. Do not edit.
// Subscriber table: engine/phases_generated.odin (with the Phase enum).

import "moonhug:engine"
import physics2d "moonhug:packages/physics2d"
import physics3d "moonhug:packages/physics3d"
import serialization "moonhug:engine/serialization"
import tween "moonhug:packages/tween"

// The enum lives in engine so packages can name keys in code.
Phase :: engine.Phase

phase_run :: proc(key: Phase) {
	#partial switch key {
	case .Init:
		app_init()
		game_bootstrap()
	case .Shutdown:
		app_shutdown()
	case .DebugDraw:
		physics2d.debug_draw()
		physics3d.debug_draw()
	case .SerializationInit:
		serialization.init()
		serialization.register_component_serializers()
		tween.tween_serialization_init()
	}
}
