package app

// Code generated by phase_gen. Do not edit.
// Subscriber table: engine/core/phases_generated.odin (with the Phase enum).

import "moonhug:engine"
import audio "moonhug:packages/audio"
import physics2d "moonhug:packages/physics2d"
import physics3d "moonhug:packages/physics3d"
import plugin_example "moonhug:packages/plugin_example"
import serialization "moonhug:engine/serialization"
import tween "moonhug:packages/tween"

// The enum lives in moonhug:engine/core, aliased by engine.
Phase :: engine.Phase

phase_run :: proc(key: Phase) {
	#partial switch key {
	case .Init:
		app_init()
		game_bootstrap()
	case .Shutdown:
		app_shutdown()
	case .DebugDraw:
		physics2d.debug_draw()
		physics3d.debug_draw()
	case .ImportersInit:
		engine.register_builtin_importers()
		audio.audio_importers_init()
	case .SerializationInit:
		serialization.init()
		serialization.register_component_serializers()
		tween.tween_serialization_init()
	case .TweenNodesInit:
		tween.register_builtin_nodes()
		plugin_example.spinner_tween_nodes_init()
	}
}
