package app

// Code generated by update_gen. Do not edit.

import physics2d "packages:physics2d"
import physics3d "packages:physics3d"
import plugin_example "packages:plugin_example"

__update :: proc(dt: f32) {
	tween_tick(dt)
	animation_update(dt)
}

__fixed_update :: proc(fixed_dt: f32) {
	tick_lifetime(fixed_dt)
	game_tick(fixed_dt)
	plugin_example.spinner_tick(fixed_dt)
	tick_player(fixed_dt)
	physics2d.physics_step(fixed_dt)
	physics3d.physics_step(fixed_dt)
	tick_destroy(fixed_dt)
}
