package app

// Code generated by debug_draw_gen. Do not edit.

import physics2d "packages:physics2d"
import physics3d "packages:physics3d"

// Called by the app loop inside the open world camera pass when
// engine.debug_draw_enabled is on.
__debug_draw :: proc() {
	physics2d.debug_draw()
	physics3d.debug_draw()
}
