package app

// Code generated by packages_gen. Do not edit.
// Installed packages (moonhug/packages/*) — see docs/Plugins.md.

import plugin_example "packages:plugin_example"

register_packages :: proc() {
	plugin_example.register_plugin_example_components()
}
