package app

// Code generated by phase_gen. Do not edit.

Phase :: enum {
	EditorInit,
	EditorShutdown,
	Init,
	Shutdown,
	Test,
}

phase_run :: proc(key: Phase) {
	#partial switch key {
	case .Init:
		app_init()
	case .Shutdown:
		app_shutdown()
	}
}
