package app

// Code generated by update_gen. Do not edit.

import plugin_example "packages:plugin_example"

__update :: proc(dt: f32) {
	tick_lifetime(dt)
	game_tick(dt)
	plugin_example.spinner_tick(dt)
	tick_player(dt)
	tween_tick(dt)
	tick_destroy(dt)
}
