package plugin_types_gen

// plugin_types_gen: the editor's table of every type any plugin on disk
// declares (docs/Plugins.md), installed or not.
//
//   generate - moonhug/editor/plugin_types_generated.odin: `plugin_types`, one
//              row per @(typ_guid) under plugins/, by guid.
//            - moonhug/editor/inspector/plugin_deps_generated.odin: `plugin_deps`, one
//              row per (plugin, dependency) with what needs it, by scope
//              (compile, tests, content), the same scan `mh deps` runs. The
//              package inspector's Dependencies table reads it.
//
// It names a component whose plugin is not installed: the inspector's Missing
// Component row shows the type and the plugin instead of the guid
// (editor/plugin_types.odin). Read from the source, not from the scan, so a
// plugin that is not linked still counts.

import "core:fmt"
import "core:strings"
import db "../gen_db"
import "../gen_facts"

@(init)
_register :: proc "contextless" () {
	db.generator("plugin_types/generate", generate)
}

generate :: proc(w: ^db.World) -> bool {
	decls := gen_facts.plugin_types_on_disk()

	b := strings.builder_make()
	defer strings.builder_destroy(&b)

	strings.write_string(&b, "package editor\n\n")
	strings.write_string(&b, "// Code generated by plugin_types_gen. Do not edit.\n")
	strings.write_string(&b, "// Every @(typ_guid) type of every plugin and sample in plugins/, installed\n")
	strings.write_string(&b, "// or not, by guid (plugin_type_of_guid).\n\n")
	strings.write_string(&b, "plugin_types := []Plugin_Type{\n")
	for d in decls {
		fmt.sbprintf(&b, "\t{{\"%s\", \"%s\", \"%s\"}},\n", d.guid, d.name, d.pkg)
	}
	strings.write_string(&b, "}\n")

	db.emit(w, "moonhug/editor/plugin_types_generated.odin", strings.to_string(b))

	strings.builder_reset(&b)
	strings.write_string(&b, "package inspector\n\n")
	strings.write_string(&b, "// Code generated by plugin_types_gen. Do not edit.\n")
	strings.write_string(&b, "// Every dependency of every plugin and sample in plugins/, installed or\n")
	strings.write_string(&b, "// not, and what needs it: compile (an import), tests (an import from\n")
	strings.write_string(&b, "// tests/ only), content (a guid in assets/ or code). A manifest entry\n")
	strings.write_string(&b, "// with none is hand-written.\n\n")
	strings.write_string(&b, "plugin_deps := []Plugin_Dep{\n")
	for r in gen_facts.plugin_deps_on_disk() {
		fmt.sbprintf(&b, "\t{{\"%s\", \"%s\", %v, %v, %v}},\n", r.plugin, r.needs, r.compile, r.tests, r.content)
	}
	strings.write_string(&b, "}\n")
	db.emit(w, "moonhug/editor/inspector/plugin_deps_generated.odin", strings.to_string(b))
	return true
}
