package tween

import engine "moonhug:engine"
import tween_nodes "moonhug:packages/tween/nodes"
import plugin_example "moonhug:packages/plugin_example"

// Code generated by tween_gen. Do not edit.

@(typ_guid={guid="a243efe5-6e34-4d1c-886c-83928685df48"})
TweenUnion :: union #no_nil{
	Tween,
	Parallel,
	Sequence,
	tween_nodes.TweenMoveToLocal,
	tween_nodes.TweenRotateToLocal,
	tween_nodes.TweenScaleToLocal,
	plugin_example.TweenSpinnerSpeed,
}

_tick_TweenMoveToLocal :: proc(task: ^TweenUnion, delta_time: f32, ctx: TweenContext) -> TweenStatus {
	return tween_nodes.tick_TweenMoveToLocal(&task.(tween_nodes.TweenMoveToLocal), delta_time, ctx)
}

_tick_TweenRotateToLocal :: proc(task: ^TweenUnion, delta_time: f32, ctx: TweenContext) -> TweenStatus {
	return tween_nodes.tick_TweenRotateToLocal(&task.(tween_nodes.TweenRotateToLocal), delta_time, ctx)
}

_tick_TweenScaleToLocal :: proc(task: ^TweenUnion, delta_time: f32, ctx: TweenContext) -> TweenStatus {
	return tween_nodes.tick_TweenScaleToLocal(&task.(tween_nodes.TweenScaleToLocal), delta_time, ctx)
}

_tick_TweenSpinnerSpeed :: proc(task: ^TweenUnion, delta_time: f32, ctx: TweenContext) -> TweenStatus {
	return plugin_example.tick_TweenSpinnerSpeed(&task.(plugin_example.TweenSpinnerSpeed), delta_time, ctx)
}

__tween_ticks_init :: proc()
{
	tween_runner_setup()

	_tween_runner.ticks[int(engine.TypeKey.Parallel)] = tick_Parallel
	_tween_runner.ticks[int(engine.TypeKey.Sequence)] = tick_Sequence
	_tween_runner.ticks[int(engine.TypeKey.TweenMoveToLocal)] = _tick_TweenMoveToLocal
	_tween_runner.ticks[int(engine.TypeKey.TweenRotateToLocal)] = _tick_TweenRotateToLocal
	_tween_runner.ticks[int(engine.TypeKey.TweenScaleToLocal)] = _tick_TweenScaleToLocal
	_tween_runner.ticks[int(engine.TypeKey.TweenSpinnerSpeed)] = _tick_TweenSpinnerSpeed

	_tween_runner.frees[int(engine.TypeKey.Parallel)] = tween_free_Parallel
	_tween_runner.frees[int(engine.TypeKey.Sequence)] = tween_free_Sequence
}
