package docs_gen

// docs_gen: the generated half of the documentation site (docs/reference/).
//
// One page per attribute the engine defines, listing every declaration that
// carries it: the attribute as written, where the declaration lives, and the
// first sentence of its doc comment. It reads the same facts the other
// generators read and is rewritten on every build, so it cannot drift from
// the code, which is why it exists instead of a hand-written list.
//
// Odin's own attributes (private, init, test ...) are skipped: they are the
// language's, not extension points of this engine.
//
// The output is gitignored like every generated file. file:line changes on
// most edits, so a tracked copy would churn in every commit.

import "core:fmt"
import "core:os"
import "core:slice"
import "core:strings"
import db "../gen_db"
import "../gen_facts"

OUT_DIR :: "docs/reference"

// Attributes that belong to Odin. Anything else seen in the scan is one of ours.
BUILTIN := []string{
	"private", "test", "init", "fini", "static", "deferred_in", "deferred_out", "deferred_in_out", "deferred_none",
	"require", "require_results", "export", "link_name", "link_prefix", "link_suffix", "link_section", "linkage",
	"objc_class", "objc_name", "objc_type", "objc_is_class_method", "objc_implement", "objc_superclass",
	"default_calling_convention", "optimization_mode", "cold", "no_instrumentation", "instrumentation_enter",
	"instrumentation_exit", "entry_point_only", "rodata", "thread_local", "extra_linker_flags", "builtin",
	"enable_target_feature", "require_target_feature", "fast_math", "disabled", "no_sanitize_address",
	"no_sanitize_memory", "no_sanitize_thread", "warning", "deprecated",
}

Entry :: struct {
	key:     string,
	name:    string,
	pkg:     string,
	where_:  string, // repo-relative file:line
	attr:    string, // "@(key k=v ...)" as rendered by gen_facts.attr_origin
	summary: string, // first sentence of the doc comment, "" when there is none
}

@(init)
_register :: proc "contextless" () {
	db.generator("docs/generate", generate)
}

generate :: proc(w: ^db.World) -> bool {
	decls := db.get_comps_DeclInfo()
	attrs := db.get_comps(w, gen_facts.Attrs_GenComp)

	entries: [dynamic]Entry
	defer delete(entries)

	m := db.all_of(db.r(decls), db.r(attrs)); defer db.matcher_destroy(&m)
	for entity in db.matched(w, &m) {
		decl := db.get(decls, entity)
		if decl.name == "" do continue
		attr_set := db.get(attrs, entity)
		for args in attr_set.attrs {
			if slice.contains(BUILTIN, args.key) do continue
			origin := gen_facts.attr_origin(args, gen_facts.decl_rel_path(decl), decl.decl.pos.line, decl.name)
			// attr_origin renders "@(...)  file:line  name", two spaces between.
			parts := strings.split(origin, "  ", context.temp_allocator)
			append(&entries, Entry{
				key = args.key, name = decl.name, pkg = decl.pkg.name,
				where_ = len(parts) > 1 ? parts[1] : "",
				attr = parts[0],
				summary = _doc_summary(decl),
			})
		}
	}

	// (key, pkg, name): the same order every build, so the pages are stable.
	slice.sort_by(entries[:], proc(a, b: Entry) -> bool {
		if a.key != b.key do return a.key < b.key
		if a.pkg != b.pkg do return a.pkg < b.pkg
		return a.name < b.name
	})

	os.make_directory(OUT_DIR)

	index := strings.builder_make()
	defer strings.builder_destroy(&index)
	strings.write_string(&index, "---\ntitle: \"Reference\"\ndescription: \"Every extension point and what is registered through it, generated from the source on each build\"\nweight: 40\n---\n\n")
	strings.write_string(&index, "Generated by the prebuild (`moonhug/prebuild/docs_gen`) on every `make build` and `mh docs`. Not edited by hand and not committed.\n\n")
	strings.write_string(&index, "Each page is one attribute. Each row is one declaration carrying it, with the attribute as written, where the declaration lives, and the first sentence of its comment.\n\n")

	weight := 10
	i := 0
	for i < len(entries) {
		key := entries[i].key
		j := i
		for j < len(entries) && entries[j].key == key do j += 1
		group := entries[i:j]
		fmt.sbprintf(&index, "- [@(%s)](%s.md) — %d\n", key, key, len(group))
		_emit_page(w, key, group, weight)
		weight += 10
		i = j
	}
	db.emit(w, OUT_DIR + "/_index.md", strings.to_string(index))
	return true
}

@(private = "file")
_emit_page :: proc(w: ^db.World, key: string, group: []Entry, weight: int) {
	b := strings.builder_make()
	defer strings.builder_destroy(&b)
	fmt.sbprintf(&b, "---\ntitle: \"@(%s)\"\ndescription: \"%d declarations carry @(%s)\"\nweight: %d\ntags: [\"reference\", \"%s\"]\n---\n\n", key, len(group), key, weight, key)
	strings.write_string(&b, "Generated from the source on every build.\n\n")
	strings.write_string(&b, "| Declaration | Package | Where | Attribute | Summary |\n|---|---|---|---|---|\n")
	for e in group {
		fmt.sbprintf(&b, "| `%s` | %s | `%s` | `%s` | %s |\n", e.name, e.pkg, e.where_, _cell(e.attr), _cell(e.summary))
	}
	db.emit(w, fmt.tprintf("%s/%s.md", OUT_DIR, key), strings.to_string(b))
}

// The first sentence of a declaration's doc comment, as one line. Comment
// markers are stripped, lines are joined with a space, and the text stops at
// the first sentence end or paragraph break. "" when the declaration has no
// doc comment.
@(private = "file")
_doc_summary :: proc(decl: ^db.DeclInfo) -> string {
	if decl.decl == nil || decl.decl.docs == nil do return ""
	b := strings.builder_make(context.temp_allocator)
	for tok in decl.decl.docs.list {
		line := tok.text
		if strings.has_prefix(line, "//") do line = line[2:]
		if strings.has_prefix(line, "/*") do line = line[2:]
		if strings.has_suffix(line, "*/") do line = line[:len(line) - 2]
		line = strings.trim_space(line)
		if line == "" {
			if strings.builder_len(b) > 0 do break // paragraph break ends the summary
			continue
		}
		if strings.builder_len(b) > 0 do strings.write_byte(&b, ' ')
		strings.write_string(&b, line)
		if strings.has_suffix(line, ".") do break
	}
	s := strings.to_string(b)
	// Stop at the first sentence end inside the joined text as well.
	if dot := strings.index(s, ". "); dot >= 0 do s = s[:dot + 1]
	return s
}

// A markdown table cell: no pipes, no newlines.
@(private = "file")
_cell :: proc(s: string) -> string {
	out, _ := strings.replace_all(s, "|", "\\|", context.temp_allocator)
	out, _ = strings.replace_all(out, "\n", " ", context.temp_allocator)
	return out
}
