package main

// Code generated by prebuild. Do not edit.
// Generators shipped by installed packages (docs/Plugins.md): blank
// imports pull in their @(init) system registrations.

import _ "moonhug:packages/tween/gen"
