package editor

import __wnd "moonhug:editor/window"
import plugin_example_editor "../packages/plugin_example/editor"

// Code generated by editor_window_gen. Do not edit.

_register_editor_windows :: proc() {
	__wnd.register("plugin_example", "Plugin Example", plugin_example_editor.plugin_example_window_draw, 420, 200)
	__wnd.register("project_settings", "Project Settings", project_settings_window_draw, 720, 440)
}
