package editor

// Code generated by packages_gen. Do not edit.
// Editor halves of installed packages — see docs/Plugins.md.

import _ "moonhug:packages/app/editor"
import _ "moonhug:packages/physics2d/editor"
import _ "moonhug:packages/physics3d/editor"
import _ "moonhug:packages/plugin_example/editor"
