package editor

// Code generated by packages_gen. Do not edit.
// Editor halves of installed packages — see docs/Plugins.md.

import _ "packages:physics2d/editor"
import _ "packages:physics3d/editor"
import _ "packages:plugin_example/editor"
