package editor

// Code generated by phase_gen. Do not edit.
// Subscriber table: engine/core/phases_generated.odin (with the Phase enum).

import "../engine"
import app "moonhug:packages/app"
import audio "moonhug:packages/audio"
import plugin_example "moonhug:packages/plugin_example"
import serialization "moonhug:engine/serialization"
import tween "moonhug:packages/tween"
import tween_editor "moonhug:packages/tween/editor"

phase_editor_run :: proc(key: engine.Phase) {
	sim_host_is_app := sim_host_is("app")
	#partial switch key {
	case .EditorInit:
		editor_init()
		tween_editor.tween_view_install()
	case .EditorShutdown:
		editor_shutdown()
	case .Init:
		if sim_host_is_app do app.app_init()
		if sim_host_is_app do app.game_bootstrap()
	case .Shutdown:
		if sim_host_is_app do app.app_shutdown()
	case .ImportersInit:
		engine.register_builtin_importers()
		audio.audio_importers_init()
	case .SerializationInit:
		serialization.init()
		serialization.register_component_serializers()
		tween.tween_serialization_init()
	case .TweenNodesInit:
		tween.register_builtin_nodes()
		plugin_example.spinner_tween_nodes_init()
	}
}
