package editor

// Code generated by phase_gen. Do not edit.
// Subscriber table: engine/phases_generated.odin (with the Phase enum).

import "../engine"
import app "moonhug:packages/app"
import app_editor "moonhug:packages/app/editor"

phase_editor_run :: proc(key: engine.Phase) {
	sim_host_is_app := sim_host_is("app")
	#partial switch key {
	case .EditorInit:
		editor_init()
		app_editor.tween_view_install()
	case .EditorShutdown:
		editor_shutdown()
	case .Init:
		if sim_host_is_app do app.app_init()
		if sim_host_is_app do app.game_bootstrap()
	case .Shutdown:
		if sim_host_is_app do app.app_shutdown()
	}
}
