package editor

// Code generated by phase_gen. Do not edit.

import "../app"

phase_editor_run :: proc(key: app.Phase) {
	#partial switch key {
	case .EditorInit:
		editor_init()
	case .EditorShutdown:
		editor_shutdown()
	case .Init:
		app.app_init()
	case .Shutdown:
		app.app_shutdown()
	}
}
