package editor

import __engine "../engine"
import engine "../engine"
import physics2d "../packages/physics2d"

// Code generated by project_settings_gen. Do not edit.

_register_project_settings :: proc() {
	__engine.project_settings_load("Physics 2D", &physics2d.physics2d_settings)
	settings_add_tab("Physics 2D", &physics2d.physics2d_settings, typeid_of(type_of(physics2d.physics2d_settings)))
	__engine.project_settings_load("Time", &engine.time_settings)
	settings_add_tab("Time", &engine.time_settings, typeid_of(type_of(engine.time_settings)))
}
