package editor

// Code generated by scene_toolbar_gen. Do not edit.

_register_scene_toolbars :: proc() {
	overlay_add_item("Tools", draw_tools_overlay, 0)
	overlay_add_item("Pivot", draw_pivot_overlay, 100)
}
