package editor

// Code generated by sim_host_gen. Do not edit.
// One row per runnable package (docs/Plugins.md) - the games the editor
// can tick. Entry points come from that host's update_generated.odin.

import app "moonhug:packages/app"

Sim_Host :: struct {
	name:         string,        // package name, e.g. "app"
	path:         string,        // scan path, e.g. "moonhug/packages/app"
	update:       proc(dt: f32), // that host's __update
	fixed_update: proc(dt: f32), // that host's __fixed_update
}

sim_hosts := []Sim_Host{
	{"app", "moonhug/packages/app", app.__update, app.__fixed_update},
}
