package user_settings_gen

// user_settings_gen: per-developer preferences (host/core/user_settings.odin).
//
//   @(user_settings={name="External Tools", tab="External Tools"})
//   external_tools: External_Tools
//
// The attribute sits on a package-level VAR — the data is the registration,
// the same shape project_settings_gen uses. A plugin keeps a preference
// without the editor's own settings struct having a field for it.
//
// `name` names the file: "External Tools" -> UserSettings/external_tools.json.
// `tab` is optional. With it the setting is also a tab of the Settings window,
// labelled `tab` and drawn the same as a @(project_settings) tab. Without it
// a view edits the setting through its own menu (@(view_menu)).
//
//   generate - moonhug/editor/user_settings_generated.odin:
//              _load_user_settings() and _save_user_settings(), one call per
//              declaration. Loading also writes a missing file with the
//              defaults, so every setting has a file to edit from the first
//              run, and registers the tab of a setting with `tab`.

import "core:fmt"
import "core:slice"
import "core:strings"
import db "../gen_db"
import "../gen_facts"

_PKG_NAME :: "editor"

SettingsEntry :: struct {
	tab_name:    string, // `name`, the file slug: "Animation" -> UserSettings/animation.json
	name:        string, // the settings var
	source_pkg:  string,
	source_path: string,
	tab:         string, // `tab`, the Settings window label, "" for none
	origin:      string, // gen_facts.attr_origin, the tab's debug tooltip
}

Settings_GenComp :: struct {
	entries: [dynamic]SettingsEntry,
}

@(init)
_register :: proc "contextless" () {
	db.provider("user_settings/provide", provide)
	db.generator("user_settings/generate", generate)
}

provide :: proc(w: ^db.World) -> bool {
	_settings := db.get_or_create_comps(w, Settings_GenComp)
	decls := db.get_comps_DeclInfo()
	attrs := db.get_comps(w, gen_facts.Attrs_GenComp)

	// No proc requirement: the attribute marks a package-level var.
	m := db.all_of(db.r(decls), db.r(attrs)); defer db.matcher_destroy(&m)
	for entity in db.matched(w, &m) {
		decl := db.get(decls, entity)
		if decl.name == "" do continue
		attr_set := db.get(attrs, entity)

		entries: [dynamic]SettingsEntry
		for args in attr_set.attrs {
			if args.key != "user_settings" do continue
			tab_name := args.fields["name"]
			if tab_name == "" {
				fmt.eprintf("user_settings: %s.%s needs name=\"...\"\n", decl.pkg.name, decl.name)
				continue
			}
			append(&entries, SettingsEntry{
				tab_name    = tab_name,
				name        = decl.name,
				source_pkg  = decl.pkg.name,
				source_path = decl.pkg_path,
				tab         = args.fields["tab"],
				origin      = gen_facts.attr_origin(args, gen_facts.decl_rel_path(decl), decl.decl.pos.line, decl.name),
			})
		}

		if len(entries) > 0 {
			db.set(_settings, entity, Settings_GenComp{entries = entries})
		} else {
			delete(entries)
		}
	}
	return true
}

_qualified_name :: proc(e: SettingsEntry) -> string {
	if e.source_pkg != "" && e.source_pkg != _PKG_NAME {
		return fmt.tprintf("%s.%s", e.source_pkg, e.name)
	}
	return e.name
}

generate :: proc(w: ^db.World) -> bool {
	entries: [dynamic]SettingsEntry
	defer delete(entries)

	decls := db.get_comps_DeclInfo()
	_settings := db.get_comps(w, Settings_GenComp)
	m := db.all_of(db.r(decls), db.r(_settings)); defer db.matcher_destroy(&m)
	for entity in db.matched(w, &m) {
		tb := db.get(_settings, entity)
		for entry in tb.entries {
			append(&entries, entry)
		}
	}

	slice.sort_by(entries[:], proc(a, b: SettingsEntry) -> bool {
		if a.tab_name != b.tab_name do return a.tab_name < b.tab_name
		return a.name < b.name
	})

	b := strings.builder_make()
	defer strings.builder_destroy(&b)

	packages_used: map[string]string
	defer delete(packages_used)
	for e in entries {
		if e.source_pkg != "" && e.source_pkg != _PKG_NAME {
			if e.source_pkg not_in packages_used {
				packages_used[e.source_pkg] = fmt.tprintf("moonhug:%s", strings.trim_prefix(e.source_path, "moonhug/"))
			}
		}
	}
	import_pkgs: [dynamic]string
	defer delete(import_pkgs)
	for pkg in packages_used {
		append(&import_pkgs, pkg)
	}
	slice.sort(import_pkgs[:])

	strings.write_string(&b, "package editor\n\n")
	// Own alias for the load call: a tab owned by a package named core would
	// otherwise collide with its packages_used import. No entries (no package
	// declares settings) means no call, so no import.
	if len(entries) > 0 do strings.write_string(&b, "import __core \"moonhug:host/core\"\n")
	for pkg in import_pkgs {
		fmt.sbprintf(&b, "import %s \"%s\"\n", pkg, packages_used[pkg])
	}
	strings.write_string(&b, "\n// Code generated by user_settings_gen. Do not edit.\n\n")
	strings.write_string(&b, "_load_user_settings :: proc() {\n")
	for e in entries {
		q := _qualified_name(e)
		fmt.sbprintf(&b, "\t__core.user_settings_load(%q, &%s)\n", e.tab_name, q)
		fmt.sbprintf(&b, "\t__core.user_settings_create(%q, &%s, typeid_of(type_of(%s)))\n", e.tab_name, q, q)
		if e.tab != "" {
			fmt.sbprintf(&b, "\tsettings_add_user_tab(%q, %q, &%s, typeid_of(type_of(%s)), origin = %q)\n", e.tab, e.tab_name, q, q, e.origin)
		}
	}
	strings.write_string(&b, "}\n\n")
	strings.write_string(&b, "_save_user_settings :: proc() {\n")
	for e in entries {
		q := _qualified_name(e)
		fmt.sbprintf(&b, "\t__core.user_settings_save(%q, &%s, typeid_of(type_of(%s)))\n", e.tab_name, q, q)
	}
	strings.write_string(&b, "}\n")

	db.emit(w, "moonhug/editor/user_settings_generated.odin", strings.to_string(b))
	return true
}
