package tests

// Code generated by packages_gen. Do not edit.
// Installed packages' test suites — run via `odin test moonhug/tests
// -all-packages` (run_tests.sh); see docs/Plugins.md.

import _ "moonhug:packages/app/tests"
import _ "moonhug:packages/audio/tests"
import _ "moonhug:packages/node_graph/tests"
import _ "moonhug:packages/physics2d/tests"
import _ "moonhug:packages/physics3d/tests"
import _ "moonhug:packages/plugin_example/tests"
import _ "moonhug:packages/prefabs_example/tests"
import _ "moonhug:packages/tween/tests"
