package tests

// Code generated by packages_gen. Do not edit.
// Installed packages' test suites — run via `odin test moonhug/tests
// -all-packages` (run_tests.sh); see docs/Plugins.md.

import _ "packages:physics2d/tests"
import _ "packages:physics3d/tests"
