package mh

// The Packages reference: one page per package of the host, the editor shell
// and every installed plugin, built from Odin's own type-checked output.
//
// `odin doc -doc-format` writes every package an entry file imports into one
// binary .odin-doc file (core:odin/doc-format). The entry file here imports
// each documented package blank, the way pkg.odin-lang.org documents Odin's
// own libraries. Each page lists the package's public declarations by kind,
// with signatures whose types link to the package that declares them, the
// declaration's attributes linked to their reference pages, its doc comment
// and its file:line.
//
// Pages sit in one folder per layer (host, editor, then each plugin by name),
// like the other reference sections. gen_facts.pkg_page in the prebuild names
// the same paths, so attribute pages can link here.

import "core:fmt"
import "core:os"
import "core:path/filepath"
import "core:slice"
import "core:strings"
import doc "core:odin/doc-format"

DOCS_ALL_DIR :: "builds/docs_all"
DOCS_ALL_FILE :: DOCS_ALL_DIR + "/all.odin"
DOCS_ALL_DOC :: DOCS_ALL_DIR + "/all.odin-doc"

Pkg_Page :: struct {
	repo_path:   string, // moonhug/packages/engine/editor/undo
	import_path: string, // moonhug:packages/engine/editor/undo
	layer:       string, // host, editor, or the plugin's name
	order:       int,    // 0 host, 1 editor, 2 plugins
	slug:        string, // editor_undo: the page's file name inside its layer folder
	real:        string, // the absolute directory odin doc reports, links resolved
	pkg:         int,    // index into the doc file's packages, 0 when not found
}

// What renders a declaration: the doc file, the page being written, and where
// every package and attribute page is.
@(private = "file")
Render :: struct {
	h:        ^doc.Header,
	files:    []doc.File,
	pkgs:     []doc.Pkg,
	ents:     []doc.Entity,
	types:    []doc.Type,
	page_of:  map[int]^Pkg_Page, // doc package index -> its page
	attr_url: map[string]string, // attribute name -> its page, relative to a package page
	current:  ^Pkg_Page,
}

docs_write_package_pages :: proc() -> bool {
	pages := _documented_packages()
	if len(pages) == 0 {
		fmt.eprintln("mh: no packages to document")
		return false
	}

	// One entry file that imports every documented package, one odin doc run.
	os.make_directory_all(DOCS_ALL_DIR)
	entry := strings.builder_make(context.temp_allocator)
	strings.write_string(&entry, "package docs_all\n\n// Written by mh docs: imports every documented package for odin doc.\n\n")
	for &p in pages do fmt.sbprintf(&entry, "import _ \"%s\"\n", p.import_path)
	if err := os.write_entire_file(DOCS_ALL_FILE, transmute([]byte)strings.to_string(entry)); err != nil {
		fmt.eprintfln("mh: cannot write %s: %v", DOCS_ALL_FILE, err)
		return false
	}
	os.remove(DOCS_ALL_DOC)
	if !step("odin doc", "odin", "doc", DOCS_ALL_FILE, "-file", "-all-packages", "-doc-format", COLLECTION, IGNORE_ATTRS, fmt.tprintf("-out:%s", DOCS_ALL_DOC)) do return false

	data, rerr := os.read_entire_file(DOCS_ALL_DOC, context.allocator)
	if rerr != nil {
		fmt.eprintfln("mh: cannot read %s: %v", DOCS_ALL_DOC, rerr)
		return false
	}
	defer delete(data)
	h, herr := doc.read_from_bytes(data)
	if herr != nil {
		fmt.eprintfln("mh: %s is not a doc file this Odin reads: %v", DOCS_ALL_DOC, herr)
		return false
	}

	r := Render{
		h     = h,
		files = doc.from_array(&h.base, h.files),
		pkgs  = doc.from_array(&h.base, h.pkgs),
		ents  = doc.from_array(&h.base, h.entities),
		types = doc.from_array(&h.base, h.types),
	}
	r.page_of = make(map[int]^Pkg_Page, context.temp_allocator)
	by_real := make(map[string]^Pkg_Page, context.temp_allocator)
	for &p in pages do by_real[p.real] = &p
	for pk, i in r.pkgs {
		if p, ok := by_real[_s(&r, pk.fullpath)]; ok {
			p.pkg = i
			r.page_of[i] = p
		}
	}
	r.attr_url = _attribute_pages()

	// Generated and gitignored: rewritten whole, so a removed package leaves no page.
	os.remove_all(DOCS_PKG_DIR)
	os.make_directory_all(DOCS_PKG_DIR)

	index := strings.builder_make(context.temp_allocator)
	strings.write_string(&index, "---\ntitle: \"Packages\"\ndescription: \"Every public declaration of the host, the editor and each installed plugin\"\nweight: 20\n---\n\n")
	strings.write_string(&index, "Generated by `mh docs` from `odin doc -doc-format`. Not edited by hand and not committed.\n\n")
	strings.write_string(&index, "Every public declaration of each package, with its signature, attributes and comment. A type in a signature links to the package that declares it. Packages are grouped by layer, `host`, `editor`, then each plugin by name, and each page names the import path a package writes.\n\n")

	layer_index := strings.builder_make(context.temp_allocator)
	layer := ""
	layer_count := 0
	plugin_rank := 0
	flush :: proc(layer: string, b: ^strings.Builder) -> bool {
		if layer == "" do return true
		path := fmt.tprintf("%s/%s/_index.md", DOCS_PKG_DIR, layer)
		if err := os.write_entire_file(path, transmute([]byte)strings.to_string(b^)); err != nil {
			fmt.eprintfln("mh: cannot write %s: %v", path, err)
			return false
		}
		strings.builder_reset(b)
		return true
	}
	missing := 0
	for &p, i in pages {
		if p.layer != layer {
			if !flush(layer, &layer_index) do return false
			if layer != "" do fmt.sbprintf(&index, "- [%s](%s/_index.md) — %d %s\n", layer, layer, layer_count, layer_count == 1 ? "package" : "packages")
			layer = p.layer
			layer_count = 0
			if p.order >= 2 do plugin_rank += 1
			os.make_directory_all(fmt.tprintf("%s/%s", DOCS_PKG_DIR, layer))
			fmt.sbprintf(&layer_index, "---\ntitle: \"%s\"\ndescription: \"Packages of %s\"\nweight: %d\n---\n\nGenerated by `mh docs` from `odin doc -doc-format`. Not edited by hand and not committed.\n\n", layer, _layer_noun(layer, p.order), (p.order + 1) * 10 + (p.order >= 2 ? plugin_rank : 0))
		}
		if p.pkg == 0 {
			// Imported by the entry file but absent from the doc file: a
			// package with no declarations, or one odin doc skipped.
			missing += 1
			continue
		}
		layer_count += 1
		summary := _first_sentence(_docs_markdown(_s(&r, r.pkgs[p.pkg].docs)))
		fmt.sbprintf(&layer_index, "- [`%s`](%s.md)%s\n", p.import_path, p.slug, summary == "" ? "" : fmt.tprintf(" — %s", summary))
		r.current = &p
		if !_write_package_page(&r, &p, (i + 1) * 10) do return false
	}
	if !flush(layer, &layer_index) do return false
	if layer != "" do fmt.sbprintf(&index, "- [%s](%s/_index.md) — %d %s\n", layer, layer, layer_count, layer_count == 1 ? "package" : "packages")
	if err := os.write_entire_file(DOCS_PKG_DIR + "/_index.md", transmute([]byte)strings.to_string(index)); err != nil {
		fmt.eprintfln("mh: cannot write %s/_index.md: %v", DOCS_PKG_DIR, err)
		return false
	}
	if missing > 0 do fmt.printfln("mh: %d packages have no entry in the doc file and no page", missing)
	return true
}

// Every package of the host, the editor and each installed plugin. Plugins are
// read through their moonhug/packages link, so a page names the import path a
// plugin writes. Tests, generators, run configs and samples are skipped: a
// sample is installed as its own link and documented through it.
@(private = "file")
_documented_packages :: proc() -> []Pkg_Page {
	dirs := make([dynamic]string, context.temp_allocator)
	for root in ([]string{"moonhug/host", "moonhug/registration", "moonhug/editor"}) do _collect_package_dirs(root, &dirs)
	handle, oerr := os.open(PACKAGES_DIR)
	if oerr == nil {
		defer os.close(handle)
		if entries, rerr := os.read_dir(handle, -1, context.temp_allocator); rerr == nil {
			for e in entries {
				if strings.has_prefix(e.name, ".") do continue
				_collect_package_dirs(fmt.tprintf("%s/%s", PACKAGES_DIR, e.name), &dirs)
			}
		}
	}
	pages := make([dynamic]Pkg_Page, context.temp_allocator)
	for d in dirs {
		layer, order, slug := pkg_page(d)
		real, ok := _real_dir(d)
		if !ok do continue
		append(&pages, Pkg_Page{repo_path = d, import_path = fmt.tprintf("moonhug:%s", d[len("moonhug/"):]), layer = layer, order = order, slug = slug, real = real})
	}
	slice.sort_by(pages[:], proc(a, b: Pkg_Page) -> bool {
		if a.order != b.order do return a.order < b.order
		if a.layer != b.layer do return a.layer < b.layer
		return a.repo_path < b.repo_path
	})
	return pages[:]
}

@(private = "file")
_collect_package_dirs :: proc(dir: string, out: ^[dynamic]string) {
	handle, oerr := os.open(dir)
	if oerr != nil do return
	defer os.close(handle)
	entries, rerr := os.read_dir(handle, -1, context.temp_allocator)
	if rerr != nil do return
	has_odin := false
	for e in entries {
		name := e.name
		if strings.has_prefix(name, ".") do continue
		if strings.has_suffix(name, ".odin") {
			has_odin = true
			continue
		}
		switch name {
		case "tests", "gen", "external", "run_configs", "samples", "assets", "docs":
			continue
		}
		sub := fmt.tprintf("%s/%s", dir, name)
		if os.is_dir(sub) do _collect_package_dirs(sub, out)
	}
	if has_odin do append(out, strings.clone(dir, context.temp_allocator))
}

// The layer, its order and the page name of a package, from its repo path:
// moonhug/host/core is host/core, moonhug/editor/undo is editor/undo,
// moonhug/packages/engine/editor/undo is engine/editor_undo. The prebuild's
// gen_facts.pkg_page is the same rule, keep the two in step.
pkg_page :: proc(repo_path: string) -> (layer: string, order: int, slug: string) {
	under :: proc(path, root: string) -> (rest: string, ok: bool) {
		if path == root do return "", true
		if strings.has_prefix(path, root) && path[len(root)] == '/' do return path[len(root) + 1:], true
		return "", false
	}
	flat :: proc(s: string) -> string {
		out, _ := strings.replace_all(s, "/", "_", context.temp_allocator)
		return out
	}
	if rest, ok := under(repo_path, "moonhug/host"); ok do return "host", 0, rest == "" ? "host" : flat(rest)
	if _, ok := under(repo_path, "moonhug/registration"); ok do return "host", 0, "registration"
	if rest, ok := under(repo_path, "moonhug/editor"); ok do return "editor", 1, rest == "" ? "editor" : flat(rest)
	if rest, ok := under(repo_path, "moonhug/packages"); ok {
		name, sub := rest, ""
		if slash := strings.index_byte(rest, '/'); slash >= 0 do name, sub = rest[:slash], rest[slash + 1:]
		return name, 2, sub == "" ? name : flat(sub)
	}
	return repo_path, 3, flat(repo_path)
}

@(private = "file")
_layer_noun :: proc(layer: string, order: int) -> string {
	switch order {
	case 0: return "the host"
	case 1: return "the editor shell"
	}
	return fmt.tprintf("the %s plugin", layer)
}

// The absolute directory with every symlink resolved, the form odin doc
// reports a package's path in.
@(private = "file")
_real_dir :: proc(dir: string) -> (string, bool) {
	abs, err := os.get_absolute_path(dir, context.temp_allocator)
	if err != nil do return "", false
	// Resolve one component at a time: plugin links point into plugins/, and a
	// sample's link points through its plugin's link.
	parts := strings.split(abs, "/", context.temp_allocator)
	cur := ""
	for part, i in parts {
		if i == 0 && part == "" do continue
		next := fmt.tprintf("%s/%s", cur, part)
		for _ in 0 ..< 8 {
			target, lerr := os.read_link(next, context.temp_allocator)
			if lerr != nil do break
			if !strings.has_prefix(target, "/") do target = fmt.tprintf("%s/%s", cur, target)
			next, _ = filepath.clean(target, context.temp_allocator)
		}
		cur = next
	}
	return cur, true
}

// Every attribute reference page, as a link relative to a package page:
// docs/reference/attributes/<layer>/<name>.md is ../../attributes/<layer>/<name>.html.
@(private = "file")
_attribute_pages :: proc() -> map[string]string {
	out := make(map[string]string, context.temp_allocator)
	root := "docs/reference/attributes"
	h, err := os.open(root)
	if err != nil do return out
	defer os.close(h)
	layers, _ := os.read_dir(h, -1, context.temp_allocator)
	for l in layers {
		if l.type != .Directory do continue
		lh, lerr := os.open(fmt.tprintf("%s/%s", root, l.name))
		if lerr != nil do continue
		pages, _ := os.read_dir(lh, -1, context.temp_allocator)
		os.close(lh)
		for p in pages {
			if !strings.has_suffix(p.name, ".md") || p.name == "_index.md" do continue
			name := strings.trim_suffix(p.name, ".md")
			out[name] = fmt.tprintf("../../attributes/%s/%s.html", l.name, name)
		}
	}
	return out
}

@(private = "file")
_s :: proc(r: ^Render, s: doc.String) -> string {
	return doc.from_string(&r.h.base, s)
}

@(private = "file")
_arr :: proc(r: ^Render, a: $A/doc.Array($T)) -> []T {
	return doc.from_array(&r.h.base, a)
}

@(private = "file")
Section :: enum { Types, Procedures, Constants, Variables }

@(private = "file")
_write_package_page :: proc(r: ^Render, p: ^Pkg_Page, weight: int) -> bool {
	pk := r.pkgs[p.pkg]
	pkg_name := _s(r, pk.name)
	pkg_docs := _docs_markdown(_s(r, pk.docs))

	// Public declarations by section, sorted by name.
	sections: [Section][dynamic]doc.Entity_Index
	for &s in sections do s = make([dynamic]doc.Entity_Index, context.temp_allocator)
	for se in _arr(r, pk.entries) {
		e := r.ents[se.entity]
		name := _s(r, e.name)
		if name == "" || strings.has_prefix(name, "_") || .Private in e.flags do continue
		switch e.kind {
		case .Type_Name:                append(&sections[.Types], se.entity)
		case .Procedure, .Proc_Group:   append(&sections[.Procedures], se.entity)
		case .Constant:                 append(&sections[.Constants], se.entity)
		case .Variable:                 append(&sections[.Variables], se.entity)
		case .Invalid, .Import_Name, .Library_Name, .Builtin:
		}
	}
	by_name :: proc(r: ^Render, list: []doc.Entity_Index) {
		context.user_ptr = r
		slice.sort_by(list, proc(a, b: doc.Entity_Index) -> bool {
			rr := cast(^Render)context.user_ptr
			return _s(rr, rr.ents[a].name) < _s(rr, rr.ents[b].name)
		})
	}
	for &s in sections do by_name(r, s[:])

	b := strings.builder_make(context.temp_allocator)
	summary := _first_sentence(pkg_docs)
	desc := summary == "" ? fmt.tprintf("Public declarations of %s", p.import_path) : summary
	desc, _ = strings.replace_all(desc, "\"", "\\\"", context.temp_allocator)
	fmt.sbprintf(&b, "---\ntitle: \"%s\"\ndescription: \"%s\"\nweight: %d\ntags: [\"reference\", \"package\"]\n---\n\n", p.import_path, desc, weight)
	fmt.sbprintf(&b, "`import \"%s\"`", p.import_path)
	folder := p.repo_path[strings.last_index_byte(p.repo_path, '/') + 1:]
	if pkg_name != folder do fmt.sbprintf(&b, " · package `%s`", pkg_name)
	strings.write_string(&b, "\n\n")
	if pkg_docs != "" {
		strings.write_string(&b, pkg_docs)
		strings.write_string(&b, "\n\n")
	}
	titles := [Section]string{ .Types = "Types", .Procedures = "Procedures", .Constants = "Constants", .Variables = "Variables" }
	has_any := false
	for list, sec in sections {
		if len(list) == 0 do continue
		has_any = true
		fmt.sbprintf(&b, "## %s (%d)\n\n", titles[sec], len(list))
		for ei in list do _write_entity(r, &b, ei)
	}
	if !has_any do strings.write_string(&b, "No public declarations.\n")

	path := fmt.tprintf("%s/%s/%s.md", DOCS_PKG_DIR, p.layer, p.slug)
	if err := os.write_entire_file(path, transmute([]byte)strings.to_string(b)); err != nil {
		fmt.eprintfln("mh: cannot write %s: %v", path, err)
		return false
	}
	return true
}

@(private = "file")
_write_entity :: proc(r: ^Render, b: ^strings.Builder, ei: doc.Entity_Index) {
	e := r.ents[ei]
	name := _s(r, e.name)
	// Hugo's id for this heading is the name lowercased, which is also what
	// the theme's table of contents links to, so cross-links use that too.
	fmt.sbprintf(b, "### %s\n\n", name)
	// Raw HTML so type names can link, which a fenced code block cannot.
	strings.write_string(b, "<pre class=\"mh-decl\"><code>")
	for a in _arr(r, e.attributes) {
		an := _s(r, a.name)
		av := _s(r, a.value)
		strings.write_string(b, "@(")
		if url, ok := r.attr_url[an]; ok {
			fmt.sbprintf(b, "<a href=\"%s\">%s</a>", url, _html(an))
		} else {
			strings.write_string(b, _html(an))
		}
		if av != "" do fmt.sbprintf(b, "=%s", _html(av))
		strings.write_string(b, ")\n")
	}
	strings.write_string(b, _html(name))
	switch e.kind {
	case .Procedure:
		strings.write_string(b, " :: ")
		_write_type(r, b, e.type, 0)
		for w in _arr(r, e.where_clauses) do fmt.sbprintf(b, "\n\twhere %s", _html(_s(r, w)))
	case .Proc_Group:
		strings.write_string(b, " :: proc{")
		for g, i in _arr(r, e.grouped_entities) {
			if i > 0 do strings.write_string(b, ", ")
			strings.write_string(b, "\n\t")
			_write_entity_ref(r, b, g)
		}
		strings.write_string(b, ",\n}")
	case .Type_Name:
		strings.write_string(b, " :: ")
		init := _s(r, e.init_string)
		t := r.types[e.type]
		if .Type_Alias in e.flags || t.kind != .Named {
			_write_type(r, b, e.type, 0)
		} else {
			base := _arr(r, t.types)
			if strings.has_prefix(init, "distinct ") {
				strings.write_string(b, "distinct ")
				// `distinct Handle` says more than the struct it resolves to.
				if len(base) > 0 && _is_anonymous(r, base[0]) {
					_write_definition(r, b, base[0])
				} else {
					strings.write_string(b, _html(init[len("distinct "):]))
				}
			} else if len(base) > 0 {
				_write_definition(r, b, base[0])
			} else {
				strings.write_string(b, _html(init))
			}
		}
	case .Constant:
		t := r.types[e.type]
		if t.kind == .Basic && strings.has_prefix(_s(r, t.name), "untyped") {
			strings.write_string(b, " :: ")
		} else {
			strings.write_string(b, " : ")
			_write_type(r, b, e.type, 0)
			strings.write_string(b, " : ")
		}
		strings.write_string(b, _html(_s(r, e.init_string)))
	case .Variable:
		strings.write_string(b, ": ")
		_write_type(r, b, e.type, 0)
		if init := _s(r, e.init_string); init != "" do fmt.sbprintf(b, " = %s", _html(init))
	case .Invalid, .Import_Name, .Library_Name, .Builtin:
	}
	strings.write_string(b, "</code></pre>\n\n")
	if docs := _docs_markdown(_s(r, e.docs)); docs != "" {
		strings.write_string(b, docs)
		strings.write_string(b, "\n\n")
	}
	fmt.sbprintf(b, "<small><code>%s</code></small>\n\n", _html(_where(r, e.pos)))
}

// A struct, union, enum or bit_field written out with one member per line.
@(private = "file")
_write_definition :: proc(r: ^Render, b: ^strings.Builder, ti: doc.Type_Index) {
	t := r.types[ti]
	#partial switch t.kind {
	case .Struct:
		flags := transmute(doc.Type_Flags_Struct)t.flags
		strings.write_string(b, "struct")
		if t.polymorphic_params != 0 do _write_type(r, b, t.polymorphic_params, 1)
		if .Packed in flags do strings.write_string(b, " #packed")
		if .Raw_Union in flags do strings.write_string(b, " #raw_union")
		if align := _s(r, t.custom_align); align != "" do fmt.sbprintf(b, " #align(%s)", _html(align))
		for w in _arr(r, t.where_clauses) do fmt.sbprintf(b, " where %s", _html(_s(r, w)))
		fields := _arr(r, t.entities)
		tags := _arr(r, t.tags)
		if len(fields) == 0 {
			strings.write_string(b, " {}")
			return
		}
		strings.write_string(b, " {\n")
		for f, i in fields {
			fe := r.ents[f]
			strings.write_string(b, "\t")
			if .Param_Using in fe.flags do strings.write_string(b, "using ")
			fmt.sbprintf(b, "%s: ", _html(_s(r, fe.name)))
			_write_type(r, b, fe.type, 1)
			if i < len(tags) {
				if tag := _s(r, tags[i]); tag != "" do fmt.sbprintf(b, " `%s`", _html(tag))
			}
			strings.write_string(b, ",")
			if c := strings.trim_space(_s(r, fe.comment)); c != "" do fmt.sbprintf(b, " // %s", _html(c))
			strings.write_string(b, "\n")
		}
		strings.write_string(b, "}")
	case .Union:
		flags := transmute(doc.Type_Flags_Union)t.flags
		strings.write_string(b, "union")
		if t.polymorphic_params != 0 do _write_type(r, b, t.polymorphic_params, 1)
		if .No_Nil in flags do strings.write_string(b, " #no_nil")
		if .Maybe in flags do strings.write_string(b, " #maybe")
		variants := _arr(r, t.types)
		if len(variants) == 0 {
			strings.write_string(b, " {}")
			return
		}
		strings.write_string(b, " {\n")
		for v in variants {
			strings.write_string(b, "\t")
			_write_type(r, b, v, 1)
			strings.write_string(b, ",\n")
		}
		strings.write_string(b, "}")
	case .Enum:
		strings.write_string(b, "enum")
		if base := _arr(r, t.types); len(base) > 0 {
			strings.write_string(b, " ")
			_write_type(r, b, base[0], 1)
		}
		strings.write_string(b, " {\n")
		for f in _arr(r, t.entities) {
			fe := r.ents[f]
			fmt.sbprintf(b, "\t%s", _html(_s(r, fe.name)))
			if init := _s(r, fe.init_string); init != "" do fmt.sbprintf(b, " = %s", _html(init))
			strings.write_string(b, ",")
			if c := strings.trim_space(_s(r, fe.comment)); c != "" do fmt.sbprintf(b, " // %s", _html(c))
			strings.write_string(b, "\n")
		}
		strings.write_string(b, "}")
	case:
		_write_type(r, b, ti, 0)
	}
}

@(private = "file")
_is_anonymous :: proc(r: ^Render, ti: doc.Type_Index) -> bool {
	#partial switch r.types[ti].kind {
	case .Struct, .Union, .Enum, .Bit_Field: return true
	}
	return false
}

// A type as it is written in a signature. Named types link to their entry on
// the page of the package that declares them, qualified by that package's
// name when it is not the page's own.
@(private = "file")
_write_type :: proc(r: ^Render, b: ^strings.Builder, ti: doc.Type_Index, depth: int) {
	if ti == 0 {
		strings.write_string(b, "?")
		return
	}
	if depth > 8 {
		strings.write_string(b, "…")
		return
	}
	t := r.types[ti]
	elems := _arr(r, t.types)
	elem :: proc(r: ^Render, b: ^strings.Builder, elems: []doc.Type_Index, i: int, depth: int) {
		if i < len(elems) do _write_type(r, b, elems[i], depth + 1)
	}
	switch t.kind {
	case .Invalid:
		strings.write_string(b, "?")
	case .Basic:
		strings.write_string(b, _html(_s(r, t.name)))
	case .Named:
		defs := _arr(r, t.entities)
		if len(defs) > 0 {
			_write_entity_ref(r, b, defs[0])
		} else {
			strings.write_string(b, _html(_s(r, t.name)))
		}
	case .Generic:
		fmt.sbprintf(b, "$%s", _html(_s(r, t.name)))
		if len(elems) > 0 {
			strings.write_string(b, "/")
			elem(r, b, elems, 0, depth)
		}
	case .Pointer:
		strings.write_string(b, "^")
		elem(r, b, elems, 0, depth)
	case .Multi_Pointer:
		strings.write_string(b, "[^]")
		elem(r, b, elems, 0, depth)
	case .Soa_Pointer:
		strings.write_string(b, "#soa ^")
		elem(r, b, elems, 0, depth)
	case .Array:
		if len(elems) > 1 {
			strings.write_string(b, "[")
			elem(r, b, elems, 1, depth)
			strings.write_string(b, "]")
		} else {
			fmt.sbprintf(b, "[%d]", t.elem_counts[0])
		}
		elem(r, b, elems, 0, depth)
	case .Enumerated_Array:
		strings.write_string(b, "[")
		elem(r, b, elems, 0, depth)
		strings.write_string(b, "]")
		elem(r, b, elems, 1, depth)
	case .Slice:
		strings.write_string(b, "[]")
		elem(r, b, elems, 0, depth)
	case .Dynamic_Array:
		strings.write_string(b, "[dynamic]")
		elem(r, b, elems, 0, depth)
	case .Fixed_Capacity_Dynamic_Array:
		fmt.sbprintf(b, "[dynamic; %d]", t.elem_counts[0])
		elem(r, b, elems, 0, depth)
	case .Map:
		strings.write_string(b, "map[")
		elem(r, b, elems, 0, depth)
		strings.write_string(b, "]")
		elem(r, b, elems, 1, depth)
	case .Struct:
		strings.write_string(b, "struct {")
		for f, i in _arr(r, t.entities) {
			fe := r.ents[f]
			if i > 0 do strings.write_string(b, ", ")
			fmt.sbprintf(b, "%s: ", _html(_s(r, fe.name)))
			_write_type(r, b, fe.type, depth + 1)
		}
		strings.write_string(b, "}")
	case .Union:
		strings.write_string(b, "union {")
		for v, i in elems {
			if i > 0 do strings.write_string(b, ", ")
			_write_type(r, b, v, depth + 1)
		}
		strings.write_string(b, "}")
	case .Enum:
		strings.write_string(b, "enum {")
		for f, i in _arr(r, t.entities) {
			if i > 0 do strings.write_string(b, ", ")
			strings.write_string(b, _html(_s(r, r.ents[f].name)))
		}
		strings.write_string(b, "}")
	case .Parameters:
		_write_params(r, b, t, depth, true)
	case .Proc:
		flags := transmute(doc.Type_Flags_Proc)t.flags
		strings.write_string(b, "proc")
		if cc := _s(r, t.calling_convention); cc != "" && cc != "odin" do fmt.sbprintf(b, " \"%s\" ", _html(cc))
		if len(elems) > 0 {
			_write_params(r, b, r.types[elems[0]], depth, true)
		} else {
			strings.write_string(b, "()")
		}
		if .Diverging in flags {
			strings.write_string(b, " -> !")
		} else if len(elems) > 1 {
			results := r.types[elems[1]]
			rs := _arr(r, results.entities)
			if len(rs) > 0 {
				strings.write_string(b, " -> ")
				named := false
				for re in rs do if n := _s(r, r.ents[re].name); n != "" && n != "_" do named = true
				if len(rs) == 1 && !named {
					_write_type(r, b, r.ents[rs[0]].type, depth + 1)
				} else {
					_write_params(r, b, results, depth, true)
				}
			}
		}
		if .Optional_Ok in flags do strings.write_string(b, " #optional_ok")
	case .Bit_Set:
		flags := transmute(doc.Type_Flags_Bit_Set)t.flags
		strings.write_string(b, "bit_set[")
		if .Range in flags {
			op := "..<" if .Op_Lt in flags else "..="
			fmt.sbprintf(b, "%d%s%d", t.elem_counts[0], op, t.elem_counts[1])
		} else {
			elem(r, b, elems, 0, depth)
		}
		if .Underlying_Type in flags && len(elems) > 1 {
			strings.write_string(b, "; ")
			elem(r, b, elems, 1, depth)
		}
		strings.write_string(b, "]")
	case .Simd_Vector:
		fmt.sbprintf(b, "#simd[%d]", t.elem_counts[0])
		elem(r, b, elems, 0, depth)
	case .Matrix:
		fmt.sbprintf(b, "matrix[%d, %d]", t.elem_counts[0], t.elem_counts[1])
		elem(r, b, elems, 0, depth)
	case .SOA_Struct_Fixed:
		fmt.sbprintf(b, "#soa[%d]", t.elem_counts[0])
		elem(r, b, elems, 0, depth)
	case .SOA_Struct_Slice:
		strings.write_string(b, "#soa[]")
		elem(r, b, elems, 0, depth)
	case .SOA_Struct_Dynamic:
		strings.write_string(b, "#soa[dynamic]")
		elem(r, b, elems, 0, depth)
	case .Relative_Pointer, .Relative_Multi_Pointer:
		strings.write_string(b, "#relative(")
		elem(r, b, elems, 1, depth)
		strings.write_string(b, ") ")
		elem(r, b, elems, 0, depth)
	case .Bit_Field:
		strings.write_string(b, "bit_field ")
		elem(r, b, elems, 0, depth)
		strings.write_string(b, " {")
		for f, i in _arr(r, t.entities) {
			fe := r.ents[f]
			if i > 0 do strings.write_string(b, ", ")
			fmt.sbprintf(b, "%s: ", _html(_s(r, fe.name)))
			_write_type(r, b, fe.type, depth + 1)
			if fe.field_group_index < 0 do fmt.sbprintf(b, " | %d", -fe.field_group_index)
		}
		strings.write_string(b, "}")
	}
}

@(private = "file")
_write_params :: proc(r: ^Render, b: ^strings.Builder, t: doc.Type, depth: int, parens: bool) {
	if parens do strings.write_string(b, "(")
	for pe, i in _arr(r, t.entities) {
		e := r.ents[pe]
		if i > 0 do strings.write_string(b, ", ")
		if .Param_Using in e.flags do strings.write_string(b, "using ")
		if .Param_No_Alias in e.flags do strings.write_string(b, "#no_alias ")
		if .Param_Any_Int in e.flags do strings.write_string(b, "#any_int ")
		if .Param_By_Ptr in e.flags do strings.write_string(b, "#by_ptr ")
		if .Param_Const in e.flags do strings.write_string(b, "#const ")
		if .Param_CVararg in e.flags do strings.write_string(b, "#c_vararg ")
		name := _s(r, e.name)
		if name != "" do fmt.sbprintf(b, "%s: ", _html(name))
		if .Param_Ellipsis in e.flags do strings.write_string(b, "..")
		if e.type != 0 do _write_type(r, b, e.type, depth + 1)
		if init := _s(r, e.init_string); init != "" do fmt.sbprintf(b, " = %s", _html(init))
	}
	if parens do strings.write_string(b, ")")
}

// A declaration's name, linked to its entry when its package has a page, and
// qualified by its package's name when that is not the current page's.
@(private = "file")
_write_entity_ref :: proc(r: ^Render, b: ^strings.Builder, ei: doc.Entity_Index) {
	e := r.ents[ei]
	name := _s(r, e.name)
	// A specialized parametric type is named with its arguments,
	// `Pool($T=TweenPlayer, $N=64)`: written as code is, `Pool(TweenPlayer, 64)`,
	// and linked to the entry of `Pool`.
	base := name
	if paren := strings.index_byte(name, '('); paren > 0 {
		base = name[:paren]
		name = _strip_param_names(name)
	}
	pkg_index := int(r.files[e.pos.file].pkg) if int(e.pos.file) < len(r.files) else 0
	qual := ""
	if pkg_index != r.current.pkg && pkg_index != 0 {
		if pn := _s(r, r.pkgs[pkg_index].name); pn != "" do qual = fmt.tprintf("%s.", pn)
	}
	page, has_page := r.page_of[pkg_index]
	public := !strings.has_prefix(base, "_") && .Private not_in e.flags
	if !has_page || !public {
		fmt.sbprintf(b, "%s%s", _html(qual), _html(name))
		return
	}
	anchor := strings.to_lower(base, context.temp_allocator)
	href := fmt.tprintf("#%s", anchor) if page == r.current else fmt.tprintf("../%s/%s.html#%s", page.layer, page.slug, anchor)
	fmt.sbprintf(b, "<a href=\"%s\">%s%s</a>", href, _html(qual), _html(name))
}

// "Pool($T=TweenPlayer, $N=64)" -> "Pool(TweenPlayer, 64)".
@(private = "file")
_strip_param_names :: proc(name: string) -> string {
	b := strings.builder_make(context.temp_allocator)
	for i := 0; i < len(name); i += 1 {
		if name[i] == '$' {
			j := i + 1
			for j < len(name) && (name[j] == '_' || (name[j] >= 'a' && name[j] <= 'z') || (name[j] >= 'A' && name[j] <= 'Z') || (name[j] >= '0' && name[j] <= '9')) do j += 1
			if j < len(name) && name[j] == '=' {
				i = j
				continue
			}
		}
		strings.write_byte(&b, name[i])
	}
	return strings.to_string(b)
}

@(private = "file")
_where :: proc(r: ^Render, pos: doc.Position) -> string {
	if int(pos.file) >= len(r.files) || pos.file == 0 do return ""
	path := _s(r, r.files[pos.file].name)
	cwd, _ := os.get_working_directory(context.temp_allocator)
	if strings.has_prefix(path, cwd) do path = strings.trim_prefix(path[len(cwd):], "/")
	return fmt.tprintf("%s:%d", path, pos.line)
}

@(private = "file")
_html :: proc(s: string) -> string {
	if strings.index_any(s, "<>&") < 0 do return s
	out, _ := strings.replace_all(s, "&", "&amp;", context.temp_allocator)
	out, _ = strings.replace_all(out, "<", "&lt;", context.temp_allocator)
	out, _ = strings.replace_all(out, ">", "&gt;", context.temp_allocator)
	return out
}

// A doc comment as markdown: lines of a paragraph joined, a blank line between
// paragraphs, and lines indented by a tab (Odin's convention for code in a
// comment) as a fenced block.
@(private = "file")
_docs_markdown :: proc(text: string) -> string {
	if strings.trim_space(text) == "" do return ""
	b := strings.builder_make(context.temp_allocator)
	para := strings.builder_make(context.temp_allocator)
	in_code := false
	flush_para :: proc(b, para: ^strings.Builder) {
		if strings.builder_len(para^) == 0 do return
		if strings.builder_len(b^) > 0 do strings.write_string(b, "\n\n")
		strings.write_string(b, strings.to_string(para^))
		strings.builder_reset(para)
	}
	rest := text
	for line in strings.split_lines_iterator(&rest) {
		is_code := strings.has_prefix(line, "\t")
		if is_code && !in_code {
			flush_para(&b, &para)
			if strings.builder_len(b) > 0 do strings.write_string(&b, "\n\n")
			strings.write_string(&b, "```odin\n")
			in_code = true
		} else if !is_code && in_code && strings.trim_space(line) != "" {
			strings.write_string(&b, "```")
			in_code = false
		}
		if in_code {
			fmt.sbprintf(&b, "%s\n", strings.trim_prefix(line, "\t"))
			continue
		}
		trimmed := strings.trim_space(line)
		if trimmed == "" {
			flush_para(&b, &para)
			continue
		}
		if strings.builder_len(para) > 0 do strings.write_byte(&para, ' ')
		strings.write_string(&para, trimmed)
	}
	if in_code do strings.write_string(&b, "```")
	flush_para(&b, &para)
	return strings.to_string(b)
}

@(private = "file")
_first_sentence :: proc(text: string) -> string {
	s := text
	if p := strings.index(s, "\n"); p >= 0 do s = s[:p]
	if dot := strings.index(s, ". "); dot >= 0 do s = s[:dot + 1]
	if strings.has_prefix(s, "```") do return ""
	return s
}
