package editor_window_gen

// editor_window_gen: plugin-declared editor windows (docs/Plugins.md).
//
//   @(editor_window={id="physics2d", title="Physics 2D", width=420, height=240})
//   draw_physics_debug :: proc() { ... }   // window CONTENT only
//
//   generate - moonhug/editor/editor_windows_generated.odin:
//              _register_editor_windows(), one window.register call per
//              declaration. Windows open by id (window.open), usually from a
//              @(menu_item) proc.
//
// width/height are the first-shown size, applied only when imgui.ini has no
// entry for the title yet. title defaults to the id.

import "core:fmt"
import "core:slice"
import "core:strings"
import db "../gen_db"
import "../gen_facts"

_PKG_NAME :: "editor"

WindowEntry :: struct {
	id:          string,
	title:       string,
	name:        string, // draw proc
	width:       int,
	height:      int,
	source_pkg:  string,
	source_path: string,
}

Window_GenComp :: struct {
	entries: [dynamic]WindowEntry,
}

@(init)
_register :: proc "contextless" () {
	db.provider("editor_window/provide", provide)
	db.generator("editor_window/generate", generate)
}

provide :: proc(w: ^db.World) -> bool {
	_windows := db.get_or_create_comps(w, Window_GenComp)
	decls := db.get_comps_DeclInfo()
	procs := db.get_comps(w, gen_facts.Proc_GenComp)
	attrs := db.get_comps(w, gen_facts.Attrs_GenComp)

	m := db.all_of(db.r(decls), db.r(procs), db.r(attrs)); defer db.matcher_destroy(&m)
	for entity in db.matched(w, &m) {
		decl := db.get(decls, entity)
		if decl.name == "" do continue
		attr_set := db.get(attrs, entity)

		entries: [dynamic]WindowEntry
		for args in attr_set.attrs {
			if args.key != "editor_window" do continue
			id := args.fields["id"]
			if id == "" {
				fmt.eprintf("editor_window: %s.%s needs id=\"...\"\n", decl.pkg.name, decl.name)
				continue
			}
			title := args.fields["title"]
			if title == "" do title = id
			append(&entries, WindowEntry{
				id          = id,
				title       = title,
				name        = decl.name,
				width       = gen_facts.attr_int(args, "width"),
				height      = gen_facts.attr_int(args, "height"),
				source_pkg  = decl.pkg.name,
				source_path = decl.pkg_path,
			})
		}

		if len(entries) > 0 {
			db.set(_windows, entity, Window_GenComp{entries = entries})
		} else {
			delete(entries)
		}
	}
	return true
}

_qualified_name :: proc(e: WindowEntry) -> string {
	if e.source_pkg != "" && e.source_pkg != _PKG_NAME {
		return fmt.tprintf("%s.%s", e.source_pkg, e.name)
	}
	return e.name
}

_relative_import_path :: proc(out_dir: string, source_path: string) -> string {
	out_dir_slash := strings.concatenate({out_dir, "/"})
	if strings.has_prefix(source_path, out_dir_slash) {
		return source_path[len(out_dir_slash):]
	}
	out_parts := strings.split(out_dir, "/")
	src_parts := strings.split(source_path, "/")
	common := 0
	for common < len(out_parts) && common < len(src_parts) && out_parts[common] == src_parts[common] {
		common += 1
	}
	ups := len(out_parts) - common
	b := strings.builder_make()
	for _ in 0 ..< ups {
		strings.write_string(&b, "../")
	}
	for i in common ..< len(src_parts) {
		if i > common do strings.write_string(&b, "/")
		strings.write_string(&b, src_parts[i])
	}
	return strings.to_string(b)
}

generate :: proc(w: ^db.World) -> bool {
	out_dir :: "moonhug/editor"

	entries: [dynamic]WindowEntry
	defer delete(entries)

	decls := db.get_comps_DeclInfo()
	_windows := db.get_comps(w, Window_GenComp)
	m := db.all_of(db.r(decls), db.r(_windows)); defer db.matcher_destroy(&m)
	for entity in db.matched(w, &m) {
		tb := db.get(_windows, entity)
		for entry in tb.entries {
			append(&entries, entry)
		}
	}

	slice.sort_by(entries[:], proc(a, b: WindowEntry) -> bool {
		if a.id != b.id do return a.id < b.id
		return a.name < b.name
	})

	b := strings.builder_make()
	defer strings.builder_destroy(&b)

	packages_used: map[string]string
	defer delete(packages_used)
	for e in entries {
		if e.source_pkg != "" && e.source_pkg != _PKG_NAME {
			if e.source_pkg not_in packages_used {
				packages_used[e.source_pkg] = _relative_import_path(out_dir, e.source_path)
			}
		}
	}
	import_pkgs: [dynamic]string
	defer delete(import_pkgs)
	for pkg in packages_used {
		append(&import_pkgs, pkg)
	}
	slice.sort(import_pkgs[:])

	strings.write_string(&b, "package editor\n\n")
	strings.write_string(&b, "import __wnd \"moonhug:editor/window\"\n")
	for pkg in import_pkgs {
		fmt.sbprintf(&b, "import %s \"%s\"\n", pkg, packages_used[pkg])
	}
	strings.write_string(&b, "\n// Code generated by editor_window_gen. Do not edit.\n\n")
	strings.write_string(&b, "_register_editor_windows :: proc() {\n")
	for e in entries {
		fmt.sbprintf(&b, "\t__wnd.register(%q, %q, %s, %d, %d)\n",
			e.id, e.title, _qualified_name(e), e.width, e.height)
	}
	strings.write_string(&b, "}\n")

	db.emit(w, "moonhug/editor/editor_windows_generated.odin", strings.to_string(b))
	return true
}
