package inspector

import app "moonhug:packages/app"
import "../../engine"

// Code generated by decorator_gen. Do not edit.

__decorator__ButtonsExample__target :: proc(ctx: ^DrawContext) {
	if ctx.is_pre {
		decorator_button(ctx, app.be_row2, label="Row 2", row=2)
		decorator_button(ctx, app.be_wide, label="Wide w=3", row=1, weight=3)
		decorator_button(ctx, app.be_narrow, label="w=1", row=1)
		decorator_button(ctx, app.be_no_args, label="No Args", row=0)
	} else {
		decorator_button(ctx, app.be_clear_target, label="Clear (below)", row=-1)
	}
}

__decorators__ButtonsExample: []DecoratorProc

__decorator__GameSettings__playerSpeed :: proc(ctx: ^DrawContext) {
	if ctx.is_pre {
		decorator_min(ctx, 0.5)
	} else {
		decorator_min(ctx, 0.5)
	}
}

__decorator__GameSettings__maxHealth :: proc(ctx: ^DrawContext) {
	if ctx.is_pre {
		decorator_min(ctx, 5)
	} else {
		decorator_min(ctx, 5)
	}
}

__decorator__GameSettings__test :: proc(ctx: ^DrawContext) {
	if ctx.is_pre {
		decorator_readonly(ctx)
	} else {
		decorator_readonly(ctx)
	}
}

__decorator__GameSettings__gameNames :: proc(ctx: ^DrawContext) {
	if ctx.is_pre {
		decorator_header(ctx=ctx, text="Test Header")
		decorator_tooltip(ctx=ctx, desc="Tooltip message")
	} else {
		decorator_tooltip(ctx=ctx, desc="Tooltip message")
		decorator_header(ctx=ctx, text="Test Header")
	}
}

__decorator__GameSettings__dynamicInt :: proc(ctx: ^DrawContext) {
	if ctx.is_pre {
		decorator_separator(ctx)
	} else {
		decorator_separator(ctx)
	}
}

__decorators__GameSettings: []DecoratorProc

__decorator__Camera__clear_color :: proc(ctx: ^DrawContext) {
	if ctx.is_pre {
		decorator_color(ctx)
	} else {
		decorator_color(ctx)
	}
}

__decorators__Camera: []DecoratorProc

__decorator__Light__color :: proc(ctx: ^DrawContext) {
	if ctx.is_pre {
		decorator_color(ctx)
	} else {
		decorator_color(ctx)
	}
}

__decorator__Light__range :: proc(ctx: ^DrawContext) {
	if ctx.is_pre {
		decorator_min(ctx, 0)
	} else {
		decorator_min(ctx, 0)
	}
}

__decorator__Light__spot_angle :: proc(ctx: ^DrawContext) {
	if ctx.is_pre {
		decorator_min(ctx, 0)
	} else {
		decorator_min(ctx, 0)
	}
}

__decorator__Light__inner_spot_angle :: proc(ctx: ^DrawContext) {
	if ctx.is_pre {
		decorator_min(ctx, 0)
	} else {
		decorator_min(ctx, 0)
	}
}

__decorator__Light__ambient :: proc(ctx: ^DrawContext) {
	if ctx.is_pre {
		decorator_min(ctx, 0)
	} else {
		decorator_min(ctx, 0)
	}
}

__decorators__Light: []DecoratorProc

__decorator__Material__color :: proc(ctx: ^DrawContext) {
	if ctx.is_pre {
		decorator_color(ctx)
	} else {
		decorator_color(ctx)
	}
}

__decorators__Material: []DecoratorProc

__decorator__SpriteRenderer__color :: proc(ctx: ^DrawContext) {
	if ctx.is_pre {
		decorator_color(ctx)
	} else {
		decorator_color(ctx)
	}
}

__decorators__SpriteRenderer: []DecoratorProc

__decorator__Time_Settings__fixed_rate :: proc(ctx: ^DrawContext) {
	if ctx.is_pre {
		decorator_min(ctx, 1)
	} else {
		decorator_min(ctx, 1)
	}
}

__decorators__Time_Settings: []DecoratorProc

__decorator__TweenRotateToLocal__rotation :: proc(ctx: ^DrawContext) {
	if ctx.is_pre {
		decorator_euler(ctx)
	} else {
		decorator_euler(ctx)
	}
}

__decorators__TweenRotateToLocal: []DecoratorProc

init_decorators :: proc() {
	__decorators__ButtonsExample = make([]DecoratorProc, 5)
	__decorators__ButtonsExample[0] = nil
	__decorators__ButtonsExample[1] = nil
	__decorators__ButtonsExample[2] = __decorator__ButtonsExample__target
	__decorators__ButtonsExample[3] = nil
	__decorators__ButtonsExample[4] = nil
	decorator_registry[typeid_of(app.ButtonsExample)] = __decorators__ButtonsExample
	__decorators__GameSettings = make([]DecoratorProc, 13)
	__decorators__GameSettings[0] = __decorator__GameSettings__playerSpeed
	__decorators__GameSettings[1] = __decorator__GameSettings__maxHealth
	__decorators__GameSettings[2] = nil
	__decorators__GameSettings[3] = __decorator__GameSettings__test
	__decorators__GameSettings[4] = nil
	__decorators__GameSettings[5] = nil
	__decorators__GameSettings[6] = __decorator__GameSettings__gameNames
	__decorators__GameSettings[7] = __decorator__GameSettings__dynamicInt
	__decorators__GameSettings[8] = nil
	__decorators__GameSettings[9] = nil
	__decorators__GameSettings[10] = nil
	__decorators__GameSettings[11] = nil
	__decorators__GameSettings[12] = nil
	decorator_registry[typeid_of(app.GameSettings)] = __decorators__GameSettings
	__decorators__Camera = make([]DecoratorProc, 7)
	__decorators__Camera[0] = nil
	__decorators__Camera[1] = nil
	__decorators__Camera[2] = nil
	__decorators__Camera[3] = nil
	__decorators__Camera[4] = nil
	__decorators__Camera[5] = __decorator__Camera__clear_color
	__decorators__Camera[6] = nil
	decorator_registry[typeid_of(engine.Camera)] = __decorators__Camera
	__decorators__Light = make([]DecoratorProc, 8)
	__decorators__Light[0] = nil
	__decorators__Light[1] = nil
	__decorators__Light[2] = __decorator__Light__color
	__decorators__Light[3] = nil
	__decorators__Light[4] = __decorator__Light__range
	__decorators__Light[5] = __decorator__Light__spot_angle
	__decorators__Light[6] = __decorator__Light__inner_spot_angle
	__decorators__Light[7] = __decorator__Light__ambient
	decorator_registry[typeid_of(engine.Light)] = __decorators__Light
	__decorators__Material = make([]DecoratorProc, 6)
	__decorators__Material[0] = nil
	__decorators__Material[1] = nil
	__decorators__Material[2] = nil
	__decorators__Material[3] = __decorator__Material__color
	__decorators__Material[4] = nil
	__decorators__Material[5] = nil
	decorator_registry[typeid_of(engine.Material)] = __decorators__Material
	__decorators__SpriteRenderer = make([]DecoratorProc, 6)
	__decorators__SpriteRenderer[0] = nil
	__decorators__SpriteRenderer[1] = nil
	__decorators__SpriteRenderer[2] = nil
	__decorators__SpriteRenderer[3] = __decorator__SpriteRenderer__color
	__decorators__SpriteRenderer[4] = nil
	__decorators__SpriteRenderer[5] = nil
	decorator_registry[typeid_of(engine.SpriteRenderer)] = __decorators__SpriteRenderer
	__decorators__Time_Settings = make([]DecoratorProc, 1)
	__decorators__Time_Settings[0] = __decorator__Time_Settings__fixed_rate
	decorator_registry[typeid_of(engine.Time_Settings)] = __decorators__Time_Settings
	__decorators__TweenRotateToLocal = make([]DecoratorProc, 5)
	__decorators__TweenRotateToLocal[0] = nil
	__decorators__TweenRotateToLocal[1] = __decorator__TweenRotateToLocal__rotation
	__decorators__TweenRotateToLocal[2] = nil
	__decorators__TweenRotateToLocal[3] = nil
	__decorators__TweenRotateToLocal[4] = nil
	decorator_registry[typeid_of(engine.TweenRotateToLocal)] = __decorators__TweenRotateToLocal
}
