package inspector

import app "moonhug:packages/app"
import audio "moonhug:packages/audio"

// Code generated by inspector_button_gen. Do not edit.

_register_inspector_buttons :: proc() {
	{
		btns := make([]Inspector_Button, 2)
		btns[0] = {label = "Log Item", row = 0, weight = 1, show_in_array = true, invoke = proc(comp: rawptr) { app.be_log_item(cast(^app.Button_Item)comp) }}
		btns[1] = {label = "Only Standalone", row = 0, weight = 1, show_in_array = false, invoke = proc(comp: rawptr) { app.be_item_standalone(cast(^app.Button_Item)comp) }}
		inspector_buttons[typeid_of(app.Button_Item)] = btns
	}
	{
		btns := make([]Inspector_Button, 4)
		btns[0] = {label = "Ping Top", row = 1, weight = 1, show_in_array = true, invoke = proc(comp: rawptr) { app.be_ping(cast(^app.ButtonsExample)comp) }}
		btns[1] = {label = "Count++", row = 0, weight = 2, show_in_array = true, invoke = proc(comp: rawptr) { app.be_count_up(cast(^app.ButtonsExample)comp) }}
		btns[2] = {label = "Reset Count", row = 0, weight = 1, show_in_array = true, invoke = proc(comp: rawptr) { app.be_count_reset(cast(^app.ButtonsExample)comp) }}
		btns[3] = {label = "Log State", row = -1, weight = 1, show_in_array = true, invoke = proc(comp: rawptr) { app.be_log_state(cast(^app.ButtonsExample)comp) }}
		inspector_buttons[typeid_of(app.ButtonsExample)] = btns
	}
	{
		btns := make([]Inspector_Button, 2)
		btns[0] = {label = "Play", row = 0, weight = 1, show_in_array = true, invoke = proc(comp: rawptr) { audio.audio_btn_play(cast(^audio.AudioSource)comp) }}
		btns[1] = {label = "Stop", row = 0, weight = 1, show_in_array = true, invoke = proc(comp: rawptr) { audio.audio_btn_stop(cast(^audio.AudioSource)comp) }}
		inspector_buttons[typeid_of(audio.AudioSource)] = btns
	}
}
