package inspector

import app "moonhug:packages/app"

// Code generated by inspector_button_gen. Do not edit.

_register_inspector_buttons :: proc() {
	{
		btns := make([]Inspector_Button, 4)
		btns[0] = {label = "Ping", row = 1, weight = 1, invoke = proc(comp: rawptr) { app.tank_ping(cast(^app.Tank)comp) }}
		btns[1] = {label = "Clear All Refs", row = 0, weight = 2, invoke = proc(comp: rawptr) { app.tank_clear_refs(cast(^app.Tank)comp) }}
		btns[2] = {label = "Log State", row = 0, weight = 1, invoke = proc(comp: rawptr) { app.tank_log_state(cast(^app.Tank)comp) }}
		btns[3] = {label = "Log State Below", row = -1, weight = 1, invoke = proc(comp: rawptr) { app.tank_log_state_below(cast(^app.Tank)comp) }}
		inspector_buttons[typeid_of(app.Tank)] = btns
	}
}
