package context_menu_gen

// context_menu_gen: the items @(context_menu) adds to an inspected object's
// overflow menu (moonhug/editor/inspector/context_menu.odin).
//
//   provide  - recognise proc decls carrying @(context_menu={type=T, menu, order}),
//              tag them with ContextMenu_GenComp.
//   generate - moonhug/editor/inspector/context_menu_generated.odin:
//              init_context_menu_registry, one context_menu_add per item keyed
//              by typeid_of(T). Packages are imported through the moonhug:
//              collection, the type's and the proc's alike.

import "core:fmt"
import "core:slice"
import "core:strings"
import "../gen_core"
import db "../gen_db"
import "../gen_facts"

_OUT_FILE :: "moonhug/editor/inspector/context_menu_generated.odin"

// Generated files are not committed, so a checkout can still hold the copies
// older prebuilds wrote elsewhere. They name a registry that is not there and
// fail the build, so generate removes them.
_STALE_FILES := []string{
	"moonhug/editor/context_menu_generated.odin",
	"moonhug/packages/engine/editor/scene_views/context_menu_generated.odin",
}

ContextMenu_GenComp :: struct {
	type_name:   string, // the type expression as written: "sprites.SpriteRenderer"
	menu_label:  string,
	proc_name:   string,
	order:       int,
	source_pkg:  string,
	source_path: string,
	// Where the item was declared, rendered by gen_facts.attr_origin. Emitted
	// into the registration and shown in the item's tooltip with debug tooltips on.
	origin:      string,
}

@(init)
_register :: proc "contextless" () {
	db.provider("context_menu/provide", provide)
	db.generator("context_menu/generate", generate)
}

provide :: proc(w: ^db.World) -> bool {
	_menus := db.get_or_create_comps(w, ContextMenu_GenComp)
	decls := db.get_comps_DeclInfo()
	procs := db.get_comps(w, gen_facts.Proc_GenComp)
	attrs := db.get_comps(w, gen_facts.Attrs_GenComp)

	m := db.all_of(db.r(decls), db.r(procs), db.r(attrs)); defer db.matcher_destroy(&m)
	for entity in db.matched(w, &m) {
		decl := db.get(decls, entity)
		if decl.name == "" do continue
		args, found := gen_facts.attr_find(db.get(attrs, entity), "context_menu")
		if !found do continue
		type_name := args.fields["type"]
		if type_name == "" {
			fmt.eprintf("context_menu_gen: %s.%s: @(context_menu) needs type=<Type>\n", decl.pkg.name, decl.name)
			return false
		}
		menu_label := args.fields["menu"]
		if menu_label == "" do menu_label = decl.name
		db.set(_menus, entity, ContextMenu_GenComp{
			type_name   = type_name,
			menu_label  = menu_label,
			proc_name   = decl.name,
			order       = gen_facts.attr_int(args, "order"),
			source_pkg  = decl.pkg.name,
			source_path = decl.pkg_path,
			origin      = gen_facts.attr_origin(args, gen_facts.decl_rel_path(decl), decl.decl.pos.line, decl.name),
		})
	}
	return true
}

// The package a type expression qualifies with: "sprites" for
// "sprites.SpriteRenderer", "" for "Foo" or "[4]f32".
_package_from_type_name :: proc(type_name: string) -> string {
	s := type_name
	for len(s) > 0 && (s[0] == '^' || s[0] == '[') {
		if s[0] == '^' {
			s = s[1:]
			continue
		}
		close := strings.index_byte(s, ']')
		if close < 0 do return ""
		s = s[close + 1:]
	}
	if dot := strings.index_byte(s, '.'); dot > 0 do return s[:dot]
	return ""
}

generate :: proc(w: ^db.World) -> bool {
	entries: [dynamic]ContextMenu_GenComp
	defer delete(entries)
	decls := db.get_comps_DeclInfo()
	_menus := db.get_comps(w, ContextMenu_GenComp)
	m := db.all_of(db.r(decls), db.r(_menus)); defer db.matcher_destroy(&m)
	for entity in db.matched(w, &m) do append(&entries, db.get(_menus, entity)^)

	// A total order, so the file does not churn between builds.
	slice.sort_by(entries[:], proc(a, b: ContextMenu_GenComp) -> bool {
		if a.type_name != b.type_name do return a.type_name < b.type_name
		if a.order != b.order do return a.order < b.order
		return a.proc_name < b.proc_name
	})

	PKG :: "inspector"
	// Package name -> collection import path, for the types and the procs.
	imports: map[string]string
	defer delete(imports)
	for e in entries {
		if pkg := _package_from_type_name(e.type_name); pkg != "" && pkg != PKG && pkg not_in imports {
			imports[pkg] = fmt.tprintf("moonhug:packages/%s", pkg)
		}
		if e.source_pkg != "" && e.source_pkg != PKG && e.source_pkg not_in imports {
			imports[e.source_pkg] = gen_facts.pkg_import_path(e.source_path)
		}
	}
	names: [dynamic]string
	defer delete(names)
	for pkg in imports do append(&names, pkg)
	slice.sort(names[:])

	b := strings.builder_make()
	defer strings.builder_destroy(&b)
	fmt.sbprintf(&b, "package %s\n\n", PKG)
	strings.write_string(&b, "// Code generated by context_menu_gen. Do not edit.\n\n")
	for pkg in names do fmt.sbprintf(&b, "import %s %q\n", pkg, imports[pkg])
	if len(names) > 0 do strings.write_string(&b, "\n")
	strings.write_string(&b, "init_context_menu_registry :: proc() {\n")
	for e in entries {
		action := e.proc_name
		if e.source_pkg != "" && e.source_pkg != PKG do action = fmt.tprintf("%s.%s", e.source_pkg, e.proc_name)
		fmt.sbprintf(&b, "\tcontext_menu_add(typeid_of(%s), Context_Menu_Entry{{label = %q, action = %s, origin = %q}})\n", e.type_name, e.menu_label, action, e.origin)
	}
	strings.write_string(&b, "}\n")

	db.emit(w, _OUT_FILE, strings.to_string(b))
	for stale in _STALE_FILES do gen_core.RemoveStaleFile(stale)
	return true
}
