package project_settings_gen

// project_settings_gen: settings tabs for the editor's Project Settings
// window (docs/Plugins.md "Project settings").
//
//   @(project_settings={name="Physics 2D"})
//   physics2d_settings := Physics2D_Settings{gravity = GRAVITY_DEFAULT}
//
// The attribute sits on a package-level VAR — the data is the registration.
// The window draws it through the inspector, undo and persistence ride the
// struct, and the owning system consumes the var by polling.
//
//   generate - moonhug/editor/project_settings_generated.odin:
//              _register_project_settings(), one settings_add_tab call per
//              declaration.

import "core:fmt"
import "core:slice"
import "core:strings"
import db "../gen_db"
import "../gen_facts"

_PKG_NAME :: "editor"

SettingsEntry :: struct {
	tab_name:    string, // left-pane label
	name:        string, // the settings var
	source_pkg:  string,
	source_path: string,
}

Settings_GenComp :: struct {
	entries: [dynamic]SettingsEntry,
}

@(init)
_register :: proc "contextless" () {
	db.provider("project_settings/provide", provide)
	db.generator("project_settings/generate", generate)
}

provide :: proc(w: ^db.World) -> bool {
	_settings := db.get_or_create_comps(w, Settings_GenComp)
	decls := db.get_comps_DeclInfo()
	attrs := db.get_comps(w, gen_facts.Attrs_GenComp)

	// No proc requirement: the attribute marks a package-level var.
	m := db.all_of(db.r(decls), db.r(attrs)); defer db.matcher_destroy(&m)
	for entity in db.matched(w, &m) {
		decl := db.get(decls, entity)
		if decl.name == "" do continue
		attr_set := db.get(attrs, entity)

		entries: [dynamic]SettingsEntry
		for args in attr_set.attrs {
			if args.key != "project_settings" do continue
			tab_name := args.fields["name"]
			if tab_name == "" {
				fmt.eprintf("project_settings: %s.%s needs name=\"...\"\n", decl.pkg.name, decl.name)
				continue
			}
			append(&entries, SettingsEntry{
				tab_name    = tab_name,
				name        = decl.name,
				source_pkg  = decl.pkg.name,
				source_path = decl.pkg_path,
			})
		}

		if len(entries) > 0 {
			db.set(_settings, entity, Settings_GenComp{entries = entries})
		} else {
			delete(entries)
		}
	}
	return true
}

_qualified_name :: proc(e: SettingsEntry) -> string {
	if e.source_pkg != "" && e.source_pkg != _PKG_NAME {
		return fmt.tprintf("%s.%s", e.source_pkg, e.name)
	}
	return e.name
}

_relative_import_path :: proc(out_dir: string, source_path: string) -> string {
	out_dir_slash := strings.concatenate({out_dir, "/"})
	if strings.has_prefix(source_path, out_dir_slash) {
		return source_path[len(out_dir_slash):]
	}
	out_parts := strings.split(out_dir, "/")
	src_parts := strings.split(source_path, "/")
	common := 0
	for common < len(out_parts) && common < len(src_parts) && out_parts[common] == src_parts[common] {
		common += 1
	}
	ups := len(out_parts) - common
	b := strings.builder_make()
	for _ in 0 ..< ups {
		strings.write_string(&b, "../")
	}
	for i in common ..< len(src_parts) {
		if i > common do strings.write_string(&b, "/")
		strings.write_string(&b, src_parts[i])
	}
	return strings.to_string(b)
}

generate :: proc(w: ^db.World) -> bool {
	out_dir :: "moonhug/editor"

	entries: [dynamic]SettingsEntry
	defer delete(entries)

	decls := db.get_comps_DeclInfo()
	_settings := db.get_comps(w, Settings_GenComp)
	m := db.all_of(db.r(decls), db.r(_settings)); defer db.matcher_destroy(&m)
	for entity in db.matched(w, &m) {
		tb := db.get(_settings, entity)
		for entry in tb.entries {
			append(&entries, entry)
		}
	}

	slice.sort_by(entries[:], proc(a, b: SettingsEntry) -> bool {
		if a.tab_name != b.tab_name do return a.tab_name < b.tab_name
		return a.name < b.name
	})

	b := strings.builder_make()
	defer strings.builder_destroy(&b)

	packages_used: map[string]string
	defer delete(packages_used)
	for e in entries {
		if e.source_pkg != "" && e.source_pkg != _PKG_NAME {
			if e.source_pkg not_in packages_used {
				packages_used[e.source_pkg] = _relative_import_path(out_dir, e.source_path)
			}
		}
	}
	import_pkgs: [dynamic]string
	defer delete(import_pkgs)
	for pkg in packages_used {
		append(&import_pkgs, pkg)
	}
	slice.sort(import_pkgs[:])

	strings.write_string(&b, "package editor\n\n")
	// Own alias for the load call: a tab owned by the engine package would
	// otherwise collide with the packages_used "engine" import.
	strings.write_string(&b, "import __engine \"../engine\"\n")
	for pkg in import_pkgs {
		fmt.sbprintf(&b, "import %s \"%s\"\n", pkg, packages_used[pkg])
	}
	strings.write_string(&b, "\n// Code generated by project_settings_gen. Do not edit.\n\n")
	strings.write_string(&b, "_register_project_settings :: proc() {\n")
	for e in entries {
		q := _qualified_name(e)
		fmt.sbprintf(&b, "\t__engine.project_settings_load(%q, &%s)\n", e.tab_name, q)
		fmt.sbprintf(&b, "\tsettings_add_tab(%q, &%s, typeid_of(type_of(%s)))\n", e.tab_name, q, q)
	}
	strings.write_string(&b, "}\n")

	db.emit(w, "moonhug/editor/project_settings_generated.odin", strings.to_string(b))
	return true
}
