package core

// Code generated by phase_gen. Do not edit.
//
// Phases -> subscribers (order, proc, package). Mode tags only where a
// subscriber is single-binary; no tag = both dispatchers.
//
// EditorInit [Editor]
//       0  editor_init  editor  [Editor]
//       1  tween_view_install  packages:tween/editor  [Editor]
// EditorShutdown [Editor]
//       0  editor_shutdown  editor  [Editor]
// ExitingEditMode
// EnteredPlayMode
// ExitingPlayMode
// EnteredEditMode
// Init
//       0  app_init  packages:app
//       1  game_bootstrap  packages:app
// Shutdown
//       0  app_shutdown  packages:app
// DebugDraw [App]
//       0  debug_draw  packages:physics2d  [App]
//       0  debug_draw  packages:physics3d  [App]
// SerializationInit
//    -200  init  serialization
//       0  register_component_serializers  serialization
//       1  tween_serialization_init  packages:tween
// Test

Phase :: enum {
	EditorInit,
	EditorShutdown,
	ExitingEditMode,
	EnteredPlayMode,
	ExitingPlayMode,
	EnteredEditMode,
	Init,
	Shutdown,
	DebugDraw,
	SerializationInit,
	Test,
}
